### ISSUE TITLE
test errors: CUDNN_STATUS_NOT_SUPPORTED and NameError

### ISSUE THREAD

**Issue by ziyuang** [Theano/Theano#2587]
Head: 238d2a84
Environment: Ubuntu 14.04 + Python 2.7.6 + GRID K520 + CUDA 6.5 + cuDNN v2 rc3
Installed via `python setup.py develop`

`.theanorc:`

    [global]
    device = cpu
    floatX = float32
    optimizer_including = cudnn
    [blas]
    ldflags = -lmkl_rt
    [nvcc]
    fastmath = True

Sample output of `theano-test`:

    ======================================================================
    ERROR: theano.sandbox.cuda.tests.test_conv_cuda_ndarray.test_full((1, 2, 6, 8), (1, 2, 2, 2), 'full', (1, 1), (2, 2), (1, 1), -1, 0, True, None, 208, 1e-05, 1e-08, 0, False, None, <theano.compile.mode.Mode object at 0x7f85f61fda10>, None)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/ubuntu/repositories/theano/theano/sandbox/cuda/tests/test_conv_cuda_ndarray.py", line 205, in _params_allgood
        gpuval = f(img, kern)
      File "/home/ubuntu/repositories/theano/theano/compile/function_module.py", line 606, in __call__
        storage_map=self.fn.storage_map)
      File "/home/ubuntu/repositories/theano/theano/compile/function_module.py", line 595, in __call__
        outputs = self.fn()
    RuntimeError: GpuDnnConvGradI: error doing operation: CUDNN_STATUS_NOT_SUPPORTED
    Apply node that caused the error: GpuDnnConvGradI{inplace=True}(GpuContiguous.0, CopyOnNegativeStrides.0, GpuAlloc{memset_0=True}.0, GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='cross'}.0, Constant{1.0})
    Inputs types: [CudaNdarrayType(float32, (False, True, False, False)), CudaNdarrayType(float32, (True, False, False, False)), CudaNdarrayType(float32, (True, True, False, False)), <theano.gof.type.CDataType object at 0x7f85c75ccf50>, Scalar(float32)]
    Inputs shapes: [(2, 1, 2, 2), (1, 2, 3, 4), (1, 1, 4, 5), 'No shapes', ()]
    Inputs strides: [(4, 0, 2, 1), (0, 48, 16, 2), (0, 0, 5, 1), 'No strides', ()]
    Inputs values: ['not shown', 'not shown', 'not shown', <PyCObject object at 0x7f85dbdf1670>, 1.0]
    
    HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
    HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

    ======================================================================
    ERROR: test_infer_shape (theano.sandbox.cuda.tests.test_extra_ops.TestGpuCumsum)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/ubuntu/repositories/theano/theano/tensor/tests/test_extra_ops.py", line 51, in test_infer_shape
        self.op_class)
      File "/home/ubuntu/repositories/theano/theano/tests/unittest_tools.py", line 237, in _compile_and_check
        outputs_function = theano.function(inputs, outputs, mode=mode)
      File "/home/ubuntu/repositories/theano/theano/compile/function.py", line 265, in function
        profile=profile)
      File "/home/ubuntu/repositories/theano/theano/compile/pfunc.py", line 511, in pfunc
        on_unused_input=on_unused_input)
      File "/home/ubuntu/repositories/theano/theano/compile/function_module.py", line 1557, in orig_function
        defaults)
      File "/home/ubuntu/repositories/theano/theano/compile/function_module.py", line 1415, in create
        input_storage=input_storage_lists)
      File "/home/ubuntu/repositories/theano/theano/gof/link.py", line 525, in make_thunk
        output_storage=output_storage)[:3]
      File "/home/ubuntu/repositories/theano/theano/gof/vm.py", line 897, in make_all
        no_recycling))
      File "/home/ubuntu/repositories/theano/theano/sandbox/cuda/__init__.py", line 256, in make_thunk
        compute_map, no_recycling)
      File "/home/ubuntu/repositories/theano/theano/gof/op.py", line 739, in make_thunk
        output_storage=node_output_storage)
      File "/home/ubuntu/repositories/theano/theano/gof/cc.py", line 1072, in make_thunk
        keep_lock=keep_lock)
      File "/home/ubuntu/repositories/theano/theano/gof/cc.py", line 1014, in __compile__
        keep_lock=keep_lock)
      File "/home/ubuntu/repositories/theano/theano/gof/cc.py", line 1433, in cthunk_factory
        key = self.cmodule_key()
      File "/home/ubuntu/repositories/theano/theano/gof/cc.py", line 1153, in cmodule_key
        compile_args=self.compile_args(),
      File "/home/ubuntu/repositories/theano/theano/gof/cc.py", line 862, in compile_args
        ret += x.c_compile_args()
      File "/home/ubuntu/repositories/theano/theano/gof/cc.py", line 1786, in __hide
        raise MethodNotDefined()
    NameError: ('The following error happened while compiling the node', GpuFlatten{1}(GpuFromHost.0), '\n', "global name 'MethodNotDefined' is not defined")
    
    ======================================================================
    FAIL: theano.sandbox.cuda.tests.test_conv_cuda_ndarray.TestConvWithPadding.test_numeric_value((5, 10, 8, 8), (12, 10, 4, 4), 3, <function dnn_conv at 0x7f85fbdf3050>)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/ubuntu/repositories/theano/theano/sandbox/cuda/tests/test_conv_cuda_ndarray.py", line 692, in _run_onecase
        Y = op(X, kern, border_mode=border_mode)
      File "/home/ubuntu/repositories/theano/theano/sandbox/cuda/dnn.py", line 702, in dnn_conv
        subsample)
      File "/home/ubuntu/repositories/theano/theano/sandbox/cuda/dnn.py", line 471, in get_out_shape
        assert border_mode == 'valid'
    AssertionError
    
The full output is available [here](http://pastebin.com/pbyRSVxL).

**Comment by abergeron** [comment]
It seems the convolution tests do not like optimizer_including='cudnn'.

Generally speaking, the tests are designed to run with the default theano configuration and will make the necessary changes to enable things like the gpu or cudnn.  What you should try is to rename your .theanorc file to something else and run the tests again.  If you get any failures then you should report them.

**Comment by nouiz** [comment]
Also update Theano. The GpuFlatten error is fixed now.

**Comment by ziyuang** [comment]
I rename the `.theanorc`, and the `CUDNN_STATUS_NOT_SUPPORTED`is still there. There is also some `CUDNN_STATUS_BAD_PARAM`:


    ======================================================================
    ERROR: theano.sandbox.cuda.tests.test_conv_cuda_ndarray.test_dnn_full((3, 2, 8, 8), (4, 2, 2, 3), 'full', (1, 1), (2, 2), (1, 1), -1, 0, True, None, 231, 1e-05, 1e-08, 0, False, None, <theano.compile.mode.Mode object at 0x7f9ce2399790>, <class 'theano.sandbox.cuda.dnn.DnnBase'>)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/ubuntu/repositories/theano/theano/sandbox/cuda/tests/test_conv_cuda_ndarray.py", line 205, in _params_allgood
        gpuval = f(img, kern)
      File "/home/ubuntu/repositories/theano/theano/compile/function_module.py", line 606, in __call__
        storage_map=self.fn.storage_map)
      File "/home/ubuntu/repositories/theano/theano/compile/function_module.py", line 595, in __call__
        outputs = self.fn()
    RuntimeError: GpuDnnConvGradI: error doing operation: CUDNN_STATUS_NOT_SUPPORTED
    Apply node that caused the error: GpuDnnConvGradI{inplace=True}(GpuContiguous.0, CopyOnNegativeStrides.0, GpuAlloc{memset_0=True}.0, GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='cross'}.0, Constant{1.0})
    Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), <theano.gof.type.CDataType object at 0x7f9ce19d5dd0>, Scalar(float32)]
    Inputs shapes: [(2, 4, 2, 3), (3, 2, 4, 4), (3, 4, 5, 6), 'No shapes', ()]
    Inputs strides: [(24, 6, 3, 1), (128, 64, 16, 2), (120, 30, 6, 1), 'No strides', ()]
    Inputs values: ['not shown', 'not shown', 'not shown', <PyCObject object at 0x7f9ca63987b0>, 1.0]
    
    HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
    HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
    
    ======================================================================
    ERROR: theano.sandbox.cuda.tests.test_dnn.test_pooling
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/ubuntu/repositories/theano/theano/sandbox/cuda/tests/test_dnn.py", line 151, in test_pooling
        g_out = fg(data)
      File "/home/ubuntu/repositories/theano/theano/compile/function_module.py", line 606, in __call__
        storage_map=self.fn.storage_map)
      File "/home/ubuntu/repositories/theano/theano/compile/function_module.py", line 595, in __call__
        outputs = self.fn()
    RuntimeError: GpuDnnPoolGrad: error doing operation: CUDNN_STATUS_BAD_PARAM. input.shape=(1, 1, 2, 1) input_grad.shape=(1, 1, 1, 1) output.shape=(1, 1, 2, 2) output_grad.shape=(1, 1, 2, 2)
    Apply node that caused the error: GpuDnnPoolGrad(GpuContiguous.0, GpuDnnPool.0, GpuContiguous.0, GpuDnnPoolDesc{ws=(2, 2), stride=(2, 2), mode='max', pad=(1, 0)}.0)
    Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), <theano.gof.type.CDataType object at 0x7f9ca637e5d0>]
    Inputs shapes: [(1, 1, 2, 2), (1, 1, 2, 1), (1, 1, 1, 1), 'No shapes']
    Inputs strides: [(0, 0, 2, 1), (0, 0, 1, 0), (0, 0, 0, 0), 'No strides']
    Inputs values: [<CudaNdarray object at 0x7f9ca2797470>, <CudaNdarray object at 0x7f9ca25017b0>, <CudaNdarray object at 0x7f9ca43a18b0>, <PyCObject object at 0x7f9ca531baa8>]
    
    Backtrace when the node is created:
      File "/home/ubuntu/repositories/theano/theano/gradient.py", line 1241, in access_grad_cache
        term = access_term_cache(node)[idx]
    
    HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by abergeron** [comment]
It appears that the first failure (CUDNN_STATUS_NOT_SUPPORTED) happens somewhat at random, but always with GpuDnnConvGradI.  I suspect that something may be wrong in the code to compute the output shape, but I don't have the time to look into it.

If we remove the hack that tries to call the grad directly instead of doing the normal forward, then the problem disappears.  So we can either try to fix the code now or wait about a week for the placeholder convolution ops and remove that code.

**Comment by lamblin** [comment]
This may have been fixed by #2608.
Could you check if it is working for you now?

**Comment by ziyuang** [comment]
No errors and no fails now.

**Comment by nouiz** [comment]
thaks for confirmation.

**Comment by nouiz** [comment]
Ok. I close this issue as it seem fixed.
