### ISSUE TITLE
Theano does not see cuDNN

### ISSUE THREAD

**Issue by zeis** [Theano/Theano#2928]
I'm using the latest development version of Theano, on Windows 8.
I've installed cuDNN v2 for Windows by manually copying the files `cudnn.lib`, `cudnn64_65.dll`, `cudnn64_65.lib` in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\lib\x64`, and `cudnn.h` in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include`.

The problem is that Theano does not seem to see cuDNN, indeed if I run the following code

    from theano.sandbox.cuda.dnn import *
    print(dnn_available())
    print(dnn_available.msg)

I get this message (notice that this is not a partial message, it does not print any error)

    Using gpu device 0: GeForce GTX 850M
    False
    Theano can not compile with cuDNN. We got this error:

The following is my `.theanorc`

    [global]
    device = gpu
    floatX = float32

    [nvcc]
    compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin

**Comment by zeis** [comment]
I reinstalled everything from scratch and it is now working.
I used the latest version of every software: CUDA 7, cuDNN v2, Visual Studio Community 2013.

**Comment by nouiz** [comment]
thanks for the update.

**Comment by and-colonna** [comment]
I had a similar issue, however with CuDNN v3.

I looked inside dnn_available in dnn.py and added

```python
print(comp)
print(out)
print(err)```

and got as output 

```
False
b"nvcc fatal   : Cannot find compiler 'cl.exe' in PATH\r\n"
b''
```

So I realized that the compiler-bindir flag was not used. I added
```python
if config.nvcc.compiler_bindir:
                params.extend(['--compiler-bindir', config.nvcc.compiler_bindir])
```
to dnn.py, just above the NVCC_compiler.try_flags call. This fixed the issue for me. I might suggest a pull request for that.

**Comment by nouiz** [comment]
Just for follow up, this new issue have been fixed in: https://github.com/Theano/Theano/pull/3664

**Comment by rybskej** [comment]
I followed the same troubleshooting steps, but found that this wasn't generic enough of a solution for my environment:

Anaconda 3 + Py 3.5 64-bit + Theano 0.82 + CUDA 8.0 + cuDNN 5.0 + Windows 7 64-bit + Microsoft Windows 7.1 SDK (VC 10)

To pass in all environment flags during this compiler test phase, instead of cherry-picking specific settings from .theanorc [nvcc], I expect we should be appending NVCC compile_args().

Specifically:
            - params = ["-l", "cudnn", "-I" + os.path.dirname(__file__)]
            + params = ["-l", "cudnn", "-I" + os.path.dirname(__file__)] **+ nvcc_compiler.NVCC_compiler.compile_args()**

This then correctly passes all nvcc variables I've set, e.g.
[nvcc]
flags=--use-local-env --cl-version=2010
fastmath = True

**Comment by vfdev-5** [comment]
I had a similar problem (on Windows 7) with cuDNN with the same message:
```
Can not compile with cuDNN. We got this error:
```
In my case, the problem was with spaces and quotes of the %CUDA_PATH%: 
```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
```
specified in `.theanorc.txt` as (bad version)
```
[cuda]
root="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5"
```
and replaced by
```
[cuda]
root=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
```
due to [this line](https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/__init__.py#L310)
