### ISSUE TITLE
ValueError: Cannot construct a ufunc with more than 32 operands (similar to #2870)

### ISSUE THREAD

**Issue by FedericoV** [Theano/Theano#3052]
I came across this error while using theano through PyMC3.  I am doing a simple float/vector multiplication, and I get this error:

```
ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f88f64382d0>
ERROR:theano.gof.opt:SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f88f64382d0>
ERROR (theano.gof.opt): Traceback:
ERROR:theano.gof.opt:Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 188, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 74, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5773, in apply
    new_outputs = self.optimizer(node)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5720, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5720, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5720, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5720, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5708, in local_fuse
    n = maker(node, C)(*inputs).owner
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5522, in maker
    return OP(scalar_op)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/elemwise.py", line 497, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 34 and outputs = 1)

ERROR:theano.gof.opt:Traceback (most recent call last):
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 188, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 74, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5773, in apply
    new_outputs = self.optimizer(node)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5720, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5720, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5720, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5720, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5708, in local_fuse
    n = maker(node, C)(*inputs).owner
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5522, in maker
    return OP(scalar_op)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/elemwise.py", line 497, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 34 and outputs = 1)
```

The line that causes the error is this:
```
enrich_est = b * del_cells
```
where b is a float, and del_cells is a 1 dimensional boolean numpy array.

I pasted the full code to cause this here:
https://github.com/pymc-devs/pymc3/issues/772

I am using bleeding edge (built from repo) numpy and theano, linked against openBLAS, under Ubuntu.

My theano flags are:

```
floatX (('float64', 'float32', 'float16')) 
    Doc:  Default floating-point precision for python casts.

Note: float16 support is experimental, use at your own risk.
    Value:  float64

warn_float64 (('ignore', 'warn', 'raise', 'pdb')) 
    Doc:  Do an action when a tensor variable with float64 dtype is created. They can't be run on the GPU with the current(old) gpu back-end and are slow with gamer GPUs.
    Value:  ignore

cast_policy (('custom', 'numpy+floatX')) 
    Doc:  Rules for implicit type casting
    Value:  custom

int_division (('int', 'raise', 'floatX')) 
    Doc:  What to do when one computes x / y, where both x and y are of integer types
    Value:  int

device (cpu, gpu*, opencl*, cuda*) 
    Doc:  Default device for computations. If gpu*, change the default to try to move computation to it and to put shared variable of float32 on it. Do not use upper case letters, only lower case even if NVIDIA use capital letters.
    Value:  cpu

gpuarray.init_device (<type 'str'>) 
    Doc:  
             Device to initialize for gpuarray use without moving
             computations automatically.
             
    Value:  

init_gpu_device (('', 'gpu', 'gpu0', 'gpu1', 'gpu2', 'gpu3', 'gpu4', 'gpu5', 'gpu6', 'gpu7', 'gpu8', 'gpu9', 'gpu10', 'gpu11', 'gpu12', 'gpu13', 'gpu14', 'gpu15')) 
    Doc:  Initialize the gpu device to use, works only if device=cpu. Unlike 'device', setting this option will NOT move computations, nor shared variables, to the specified GPU. It can be used to run GPU-specific tests on a particular GPU.
    Value:  

force_device (<function booltype at 0x7f42a31bd848>) 
    Doc:  Raise an error if we can't use the specified device
    Value:  False

print_active_device (<function booltype at 0x7f42a31bd9b0>) 
    Doc:  Print active device at when the GPU device is initialized.
    Value:  True

assert_no_cpu_op (('ignore', 'warn', 'raise', 'pdb')) 
    Doc:  Raise an error/warning if there is a CPU op in the computational graph.
    Value:  ignore

mode (('Mode', 'ProfileMode', 'DebugMode', 'FAST_RUN', 'FAST_COMPILE', 'PROFILE_MODE', 'DEBUG_MODE')) 
    Doc:  Default compilation mode
    Value:  Mode

cxx (<type 'str'>) 
    Doc:  The C++ compiler to use. Currently only g++ is supported, but supporting additional compilers should not be too difficult. If it is empty, no C++ code is compiled.
    Value:  /usr/bin/g++

linker (('cvm', 'c|py', 'py', 'c', 'c|py_nogc', 'vm', 'vm_nogc', 'cvm_nogc')) 
    Doc:  Default linker used if the theano flags mode is Mode or ProfileMode(deprecated)
    Value:  cvm

allow_gc (<function booltype at 0x7f42a24555f0>) 
    Doc:  Do we default to delete intermediate results during Theano function calls? Doing so lowers the memory requirement, but asks that we reallocate memory at the next function call. This is implemented for the default linker, but may not work for all linkers.
    Value:  True

optimizer (('fast_run', 'merge', 'fast_compile', 'None')) 
    Doc:  Default optimizer. If not None, will use this linker with the Mode object (not ProfileMode(deprecated) or DebugMode)
    Value:  fast_run

optimizer_verbose (<function booltype at 0x7f42a24557d0>) 
    Doc:  If True, we print all optimization being applied
    Value:  False

on_opt_error (('warn', 'raise', 'pdb')) 
    Doc:  What to do when an optimization crashes: warn and skip it, raise the exception, or fall into the pdb debugger.
    Value:  warn

<theano.configparser.ConfigParam object at 0x7f42a2457750>
    Doc:  This config option was removed in 0.5: do not use it!
    Value:  True

nocleanup (<function booltype at 0x7f42a2455a28>) 
    Doc:  Suppress the deletion of code files that did not compile cleanly
    Value:  False

on_unused_input (('raise', 'warn', 'ignore')) 
    Doc:  What to do if a variable in the 'inputs' list of  theano.function() is not used in the graph.
    Value:  raise

tensor.cmp_sloppy (<type 'int'>) 
    Doc:  Relax tensor._allclose (0) not at all, (1) a bit, (2) more
    Value:  0

tensor.local_elemwise_fusion (<function booltype at 0x7f42a2455cf8>) 
    Doc:  Enable or not in fast_run mode(fast_run optimization) the elemwise fusion optimization
    Value:  True

gpu.local_elemwise_fusion (<function booltype at 0x7f42a2455e60>) 
    Doc:  Enable or not in fast_run mode(fast_run optimization) the gpu elemwise fusion optimization
    Value:  True

lib.amdlibm (<function booltype at 0x7f42a245d050>) 
    Doc:  Use amd's amdlibm numerical library
    Value:  False

gpuelemwise.sync (<function booltype at 0x7f42a245d1b8>) 
    Doc:  when true, wait that the gpu fct finished and check it error code.
    Value:  True

traceback.limit (<type 'int'>) 
    Doc:  The number of stack to trace. -1 mean all.
    Value:  7

experimental.mrg (<function booltype at 0x7f42a245d398>) 
    Doc:  Another random number generator that work on the gpu
    Value:  False

experimental.unpickle_gpu_on_cpu (<function booltype at 0x7f42a245d500>) 
    Doc:  Allow unpickling of pickled CudaNdarrays as numpy.ndarrays.This is useful, if you want to open a CudaNdarray without having cuda installed.If you have cuda installed, this will force unpickling tobe done on the cpu to numpy.ndarray.Please be aware that this may get you access to the data,however, trying to unpicke gpu functions will not succeed.This flag is experimental and may be removed any time, whengpu<>cpu transparency is solved.
    Value:  False

numpy.seterr_all (('ignore', 'warn', 'raise', 'call', 'print', 'log', 'None')) 
    Doc:  ("Sets numpy's behaviour for floating-point errors, ", "see numpy.seterr. 'None' means not to change numpy's default, which can be different for different numpy releases. This flag sets the default behaviour for all kinds of floating-point errors, its effect can be overriden for specific errors by the following flags: seterr_divide, seterr_over, seterr_under and seterr_invalid.")
    Value:  ignore

numpy.seterr_divide (('None', 'ignore', 'warn', 'raise', 'call', 'print', 'log')) 
    Doc:  Sets numpy's behavior for division by zero, see numpy.seterr. 'None' means using the default, defined by numpy.seterr_all.
    Value:  None

numpy.seterr_over (('None', 'ignore', 'warn', 'raise', 'call', 'print', 'log')) 
    Doc:  Sets numpy's behavior for floating-point overflow, see numpy.seterr. 'None' means using the default, defined by numpy.seterr_all.
    Value:  None

numpy.seterr_under (('None', 'ignore', 'warn', 'raise', 'call', 'print', 'log')) 
    Doc:  Sets numpy's behavior for floating-point underflow, see numpy.seterr. 'None' means using the default, defined by numpy.seterr_all.
    Value:  None

numpy.seterr_invalid (('None', 'ignore', 'warn', 'raise', 'call', 'print', 'log')) 
    Doc:  Sets numpy's behavior for invalid floating-point operation, see numpy.seterr. 'None' means using the default, defined by numpy.seterr_all.
    Value:  None

warn.ignore_bug_before (('0.6', 'None', 'all', '0.3', '0.4', '0.4.1', '0.5', '0.7')) 
    Doc:  If 'None', we warn about all Theano bugs found by default. If 'all', we don't warn about Theano bugs found by default. If a version, we print only the warnings relative to Theano bugs found after that version. Warning for specific bugs can be configured with specific [warn] flags.
    Value:  0.6

warn.argmax_pushdown_bug (<function booltype at 0x7f42a245d9b0>) 
    Doc:  Warn if in past version of Theano we generated a bug with the theano.tensor.nnet.nnet.local_argmax_pushdown optimization. Was fixed 27 may 2010
    Value:  False

warn.gpusum_01_011_0111_bug (<function booltype at 0x7f42a245db18>) 
    Doc:  Warn if we are in a case where old version of Theano had a silent bug with GpuSum pattern 01,011 and 0111 when the first dimensions was bigger then 4096. Was fixed 31 may 2010
    Value:  False

warn.sum_sum_bug (<function booltype at 0x7f42a245dc80>) 
    Doc:  Warn if we are in a case where Theano version between version 9923a40c7b7a and the 2 august 2010 (fixed date), generated an error in that case. This happens when there are 2 consecutive sums in the graph, bad code was generated. Was fixed 2 August 2010
    Value:  False

warn.sum_div_dimshuffle_bug (<function booltype at 0x7f42a245dde8>) 
    Doc:  Warn if previous versions of Theano (between rev. 3bd9b789f5e8, 2010-06-16, and cfc6322e5ad4, 2010-08-03) would have given incorrect result. This bug was triggered by sum of division of dimshuffled tensors.
    Value:  False

warn.subtensor_merge_bug (<function booltype at 0x7f42a245df50>) 
    Doc:  Warn if previous versions of Theano (before 0.5rc2) could have given incorrect results when indexing into a subtensor with negative stride (for instance, for instance, x[a:b:-1][c]).
    Value:  False

warn.gpu_set_subtensor1 (<function booltype at 0x7f42a2461140>) 
    Doc:  Warn if previous versions of Theano (before 0.6) could have given incorrect results when moving to the gpu set_subtensor(x[int vector], new_value)
    Value:  False

warn.vm_gc_bug (<function booltype at 0x7f42a24612a8>) 
    Doc:  There was a bug that existed in the default Theano configuration, only in the development version between July 5th 2012 and July 30th 2012. This was not in a released version. If your code was affected by this bug, a warning will be printed during the code execution if you use the `linker=vm,vm.lazy=True,warn.vm_gc_bug=True` Theano flags. This warning is disabled by default as the bug was not released.
    Value:  False

warn.signal_conv2d_interface (<function booltype at 0x7f42a2461410>) 
    Doc:  Warn we use the new signal.conv2d() when its interface changed mid June 2014
    Value:  True

warn.reduce_join (<function booltype at 0x7f42a2461578>) 
    Doc:  Your current code is fine, but Theano versions prior to 0.7 (or this development version) might have given an incorrect result. To disable this warning, set the Theano flag warn.reduce_join to False. The problem was an optimization, that modified the pattern "Reduce{scalar.op}(Join(axis=0, a, b), axis=0)", did not check the reduction axis. So if the reduction axis was not 0, you got a wrong answer.
    Value:  True

warn.inc_set_subtensor1 (<function booltype at 0x7f42a24616e0>) 
    Doc:  Warn if previous versions of Theano (before 0.7) could have given incorrect results for inc_subtensor and set_subtensor when using some patterns of advanced indexing (indexing with one vector or matrix of ints).
    Value:  True

compute_test_value (('off', 'ignore', 'warn', 'raise', 'pdb')) 
    Doc:  If 'True', Theano will run each op at graph build time, using Constants, SharedVariables and the tag 'test_value' as inputs to the function. This helps the user track down problems in the graph before it gets optimized.
    Value:  off

compute_test_value_opt (('off', 'ignore', 'warn', 'raise', 'pdb')) 
    Doc:  For debugging Theano optimization only. Same as compute_test_value, but is used during Theano optimization
    Value:  off

unpickle_function (<function booltype at 0x7f42a2461938>) 
    Doc:  Replace unpickled Theano functions with None. This is useful to unpickle old graphs that pickled them when it shouldn't
    Value:  True

reoptimize_unpickled_function (<function booltype at 0x7f42a2461aa0>) 
    Doc:  Re-optimize the graph when a theano function is unpickled from the disk.
    Value:  True

exception_verbosity (('low', 'high')) 
    Doc:  If 'low', the text of exceptions will generally refer to apply nodes with short names such as Elemwise{add_no_inplace}. If 'high', some exceptions will also refer to apply nodes with long descriptions  like:
    A. Elemwise{add_no_inplace}
            B. log_likelihood_v_given_h
            C. log_likelihood_h
    Value:  low

openmp (<function booltype at 0x7f42a2461c80>) 
    Doc:  Allow (or not) parallel computation on the CPU with OpenMP. This is the default value used when creating an Op that supports OpenMP parallelization. It is preferable to define it via the Theano configuration file ~/.theanorc or with the environment variable THEANO_FLAGS. Parallelization is only done for some operations that implement it, and even for operations that implement parallelism, each operation is free to respect this flag or not. You can control the number of threads used with the environment variable OMP_NUM_THREADS. If it is set to 1, we disable openmp in Theano by default.
    Value:  False

openmp_elemwise_minsize (<type 'int'>) 
    Doc:  If OpenMP is enabled, this is the minimum size of vectors for which the openmp parallelization is enabled in element wise ops.
    Value:  200000

check_input (<function booltype at 0x7f42a2461e60>) 
    Doc:  Specify if types should check their input in their C code. It can be used to speed up compilation, reduce overhead (particularly for scalars) and reduce the number of generated C files.
    Value:  True

cache_optimizations (<function booltype at 0x7f42a2465050>) 
    Doc:  WARNING: work in progress, does not work yet. Specify if the optimization cache should be used. This cache will any optimized graph and its optimization. Actually slow downs a lot the first optimization, and could possibly still contains some bugs. Use at your own risks.
    Value:  False

gcc.cxxflags (<type 'str'>) 
    Doc:  Extra compiler flags for gcc
    Value:  

compile.wait (<type 'int'>) 
    Doc:  Time to wait before retrying to aquire the compile lock.
    Value:  5

compile.timeout (<type 'int'>) 
    Doc:  In seconds, time that a process will wait before deciding to
override an existing lock. An override only happens when the existing
lock is held by the same owner *and* has not been 'refreshed' by this
owner for more than this period. Refreshes are done every half timeout
period for running processes.
    Value:  120

compiledir_format (<type 'str'>) 
    Doc:  Format string for platform-dependent compiled module subdirectory
(relative to base_compiledir). Available keys: gxx_version, hostname,
numpy_version, platform, processor, python_bitwidth,
python_int_bitwidth, python_version, short_platform, theano_version.
Defaults to 'compiledir_%(short_platform)s-%(processor)s-%(python_vers
ion)s-%(python_bitwidth)s'.
    Value:  compiledir_%(short_platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s

<theano.configparser.ConfigParam object at 0x7f428c55b710>
    Doc:  platform-independent root directory for compiled modules
    Value:  /home/federico/.theano

<theano.configparser.ConfigParam object at 0x7f428c55b9d0>
    Doc:  platform-dependent cache directory for compiled modules
    Value:  /home/federico/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.9-64

cmodule.mac_framework_link (<function booltype at 0x7f428c5655f0>) 
    Doc:  If set to True, breaks certain MacOS installations with the infamous Bus Error
    Value:  False

cmodule.warn_no_version (<function booltype at 0x7f428c565758>) 
    Doc:  If True, will print a warning when compiling one or more Op with C code that can't be cached because there is no c_code_cache_version() function associated to at least one of those Ops.
    Value:  False

cmodule.remove_gxx_opt (<function booltype at 0x7f428c5658c0>) 
    Doc:  If True, will remove the -O* parameter passed to g++.This is useful to debug in gdb modules compiled by Theano.The parameter -g is passed by default to g++
    Value:  False

cmodule.compilation_warning (<function booltype at 0x7f428c565a28>) 
    Doc:  If True, will print compilation warnings.
    Value:  False

cmodule.preload_cache (<function booltype at 0x7f428c565b90>) 
    Doc:  If set to True, will preload the C module cache at import time
    Value:  False

metaopt.verbose (<function booltype at 0x7f42a0787050>) 
    Doc:  Enable verbose output for meta optimizers
    Value:  False

optdb.position_cutoff (<type 'float'>) 
    Doc:  Where to stop eariler during optimization. It represent the position of the optimizer where to stop.
    Value:  inf

optdb.max_use_ratio (<type 'float'>) 
    Doc:  A ratio that prevent infinite loop in EquilibriumOptimizer.
    Value:  5.0

profile (<function booltype at 0x7f42a07a9b18>) 
    Doc:  If VM should collect profile information
    Value:  False

profile_optimizer (<function booltype at 0x7f42a07a9c80>) 
    Doc:  If VM should collect optimizer profile information
    Value:  False

profile_memory (<function booltype at 0x7f42a07a9de8>) 
    Doc:  If VM should collect memory profile information and print it
    Value:  False

<theano.configparser.ConfigParam object at 0x7f42a0741510>
    Doc:  Useful only for the vm linkers. When lazy is None, auto detect if lazy evaluation is needed and use the apropriate version. If lazy is True/False, force the version used between Loop/LoopGC and Stack.
    Value:  None

optimizer_excluding (<type 'str'>) 
    Doc:  When using the default mode, we will remove optimizer with these tags. Separate tags with ':'.
    Value:  

optimizer_including (<type 'str'>) 
    Doc:  When using the default mode, we will add optimizer with these tags. Separate tags with ':'.
    Value:  

optimizer_requiring (<type 'str'>) 
    Doc:  When using the default mode, we will require optimizer with these tags. Separate tags with ':'.
    Value:  

DebugMode.patience (<type 'int'>) 
    Doc:  Optimize graph this many times to detect inconsistency
    Value:  10

DebugMode.check_c (<function booltype at 0x7f42a0766aa0>) 
    Doc:  Run C implementations where possible
    Value:  True

DebugMode.check_py (<function booltype at 0x7f42a0766c08>) 
    Doc:  Run Python implementations where possible
    Value:  True

DebugMode.check_finite (<function booltype at 0x7f42a0766d70>) 
    Doc:  True -> complain about NaN/Inf results
    Value:  True

DebugMode.check_strides (<type 'int'>) 
    Doc:  Check that Python- and C-produced ndarrays have same strides. On difference: (0) - ignore, (1) warn, or (2) raise error
    Value:  1

DebugMode.warn_input_not_reused (<function booltype at 0x7f42a04f6050>) 
    Doc:  Generate a warning when destroy_map or view_map says that an op works inplace, but the op did not reuse the input for its output.
    Value:  True

DebugMode.check_preallocated_output (<type 'str'>) 
    Doc:  Test thunks with pre-allocated memory as output storage. This is a list of strings separated by ":". Valid values are: "initial" (initial storage in storage map, happens with Scan),"previous" (previously-returned memory), "c_contiguous", "f_contiguous", "strided" (positive and negative strides), "wrong_size" (larger and smaller dimensions), and "ALL" (all of the above).
    Value:  

DebugMode.check_preallocated_output_ndim (<type 'int'>) 
    Doc:  When testing with "strided" preallocated output memory, test all combinations of strides over that number of (inner-most) dimensions. You may want to reduce that number to reduce memory or time usage, but it is advised to keep a minimum of 2.
    Value:  4

profiling.time_thunks (<function booltype at 0x7f42a0501398>) 
    Doc:  Time individual thunks when profiling
    Value:  True

profiling.n_apply (<type 'int'>) 
    Doc:  Number of Apply instances to print by default
    Value:  20

profiling.n_ops (<type 'int'>) 
    Doc:  Number of Ops to print by default
    Value:  20

profiling.output_line_width (<type 'int'>) 
    Doc:  Max line width for the profiling output
    Value:  512

profiling.min_memory_size (<type 'int'>) 
    Doc:  For the memory profile, do not print Apply nodes if the size
             of their outputs (in bytes) is lower than this threshold
    Value:  1024

profiling.min_peak_memory (<function booltype at 0x7f42a05018c0>) 
    Doc:  The min peak memory usage of the order
    Value:  False

profiling.destination (<type 'str'>) 
    Doc:  
             File destination of the profiling output
             
    Value:  stderr

ProfileMode.n_apply_to_print (<type 'int'>) 
    Doc:  Number of apply instances to print by default
    Value:  15

ProfileMode.n_ops_to_print (<type 'int'>) 
    Doc:  Number of ops to print by default
    Value:  20

ProfileMode.min_memory_size (<type 'int'>) 
    Doc:  For the memory profile, do not print apply nodes if the size of their outputs (in bytes) is lower then this threshold
    Value:  1024

ProfileMode.profile_memory (<function booltype at 0x7f42a0511a28>) 
    Doc:  Enable profiling of memory used by Theano functions
    Value:  False

on_shape_error (('warn', 'raise')) 
    Doc:  warn: print a warning and use the default value. raise: raise an error
    Value:  warn

tensor.insert_inplace_optimizer_validate_nb (<type 'int'>) 
    Doc:  -1: auto, if graph have less then 500 nodes 1, else 10
    Value:  -1

experimental.local_alloc_elemwise (<function booltype at 0x7f4286b82758>) 
    Doc:  DEPRECATED: If True, enable the experimental optimization local_alloc_elemwise. Generates error if not True. Use optimizer_excluding=local_alloc_elemwise to dsiable.
    Value:  True

experimental.local_alloc_elemwise_assert (<function booltype at 0x7f4286b827d0>) 
    Doc:  When the local_alloc_elemwise is applied, add an assert to highlight shape errors.
    Value:  True

blas.ldflags (<type 'str'>) 
    Doc:  lib[s] to include for [Fortran] level-3 blas implementation
    Value:  -L/opt/OpenBLAS/lib -lopenblas -lopenblas

warn.identify_1pexp_bug (<function booltype at 0x7f4285b508c0>) 
    Doc:  Warn if Theano versions prior to 7987b51 (2011-12-18) could have yielded a wrong result due to a bug in the is_1pexp function
    Value:  False

scan.allow_gc (<function booltype at 0x7f42838c4398>) 
    Doc:  Allow/disallow gc inside of Scan (default: False)
    Value:  False

scan.allow_output_prealloc (<function booltype at 0x7f42838c4500>) 
    Doc:  Allow/disallow memory preallocation for outputs inside of scan (default: True)
    Value:  True

unittests.rseed (<type 'str'>) 
    Doc:  Seed to use for randomized unit tests. Special value 'random' means using a seed of None.
    Value:  666
```

**Comment by nouiz** [comment]
I think this is mixed in the development version of Theano. Can you update Theano and test it?

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by FedericoV** [comment]
Just installed the bleeding edge version.  I even tried updating GCC - I get the same error:
```
ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f9517bacbd0>
ERROR:theano.gof.opt:SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f9517bacbd0>
ERROR (theano.gof.opt): Traceback:
ERROR:theano.gof.opt:Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 194, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 79, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5788, in apply
    new_outputs = self.optimizer(node)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5723, in local_fuse
    n = maker(node, C)(*inputs).owner
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5536, in maker
    return OP(scalar_op)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/elemwise.py", line 504, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 51 and outputs = 1)

ERROR:theano.gof.opt:Traceback (most recent call last):
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 194, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 79, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5788, in apply
    new_outputs = self.optimizer(node)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5723, in local_fuse
    n = maker(node, C)(*inputs).owner
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5536, in maker
    return OP(scalar_op)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/elemwise.py", line 504, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 51 and outputs = 1)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f9517bacbd0>
ERROR:theano.gof.opt:SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f9517bacbd0>
ERROR (theano.gof.opt): Traceback:
ERROR:theano.gof.opt:Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 194, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 79, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5788, in apply
    new_outputs = self.optimizer(node)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5723, in local_fuse
    n = maker(node, C)(*inputs).owner
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5536, in maker
    return OP(scalar_op)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/elemwise.py", line 504, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 51 and outputs = 1)
```

Here is my theano config:

```
floatX (('float64', 'float32', 'float16')) 
    Doc:  Default floating-point precision for python casts.

Note: float16 support is experimental, use at your own risk.
    Value:  float64

warn_float64 (('ignore', 'warn', 'raise', 'pdb')) 
    Doc:  Do an action when a tensor variable with float64 dtype is created. They can't be run on the GPU with the current(old) gpu back-end and are slow with gamer GPUs.
    Value:  ignore

cast_policy (('custom', 'numpy+floatX')) 
    Doc:  Rules for implicit type casting
    Value:  custom

int_division (('int', 'raise', 'floatX')) 
    Doc:  What to do when one computes x / y, where both x and y are of integer types
    Value:  int

device (cpu, gpu*, opencl*, cuda*) 
    Doc:  Default device for computations. If gpu*, change the default to try to move computation to it and to put shared variable of float32 on it. Do not use upper case letters, only lower case even if NVIDIA use capital letters.
    Value:  cpu

gpuarray.init_device (<type 'str'>) 
    Doc:  
             Device to initialize for gpuarray use without moving
             computations automatically.
             
    Value:  

init_gpu_device (('', 'gpu', 'gpu0', 'gpu1', 'gpu2', 'gpu3', 'gpu4', 'gpu5', 'gpu6', 'gpu7', 'gpu8', 'gpu9', 'gpu10', 'gpu11', 'gpu12', 'gpu13', 'gpu14', 'gpu15')) 
    Doc:  Initialize the gpu device to use, works only if device=cpu. Unlike 'device', setting this option will NOT move computations, nor shared variables, to the specified GPU. It can be used to run GPU-specific tests on a particular GPU.
    Value:  

force_device (<function booltype at 0x7f951839b140>) 
    Doc:  Raise an error if we can't use the specified device
    Value:  False

print_active_device (<function booltype at 0x7f951839b2a8>) 
    Doc:  Print active device at when the GPU device is initialized.
    Value:  True

assert_no_cpu_op (('ignore', 'warn', 'raise', 'pdb')) 
    Doc:  Raise an error/warning if there is a CPU op in the computational graph.
    Value:  ignore

mode (('Mode', 'ProfileMode', 'DebugMode', 'FAST_RUN', 'FAST_COMPILE', 'PROFILE_MODE', 'DEBUG_MODE')) 
    Doc:  Default compilation mode
    Value:  Mode

cxx (<type 'str'>) 
    Doc:  The C++ compiler to use. Currently only g++ is supported, but supporting additional compilers should not be too difficult. If it is empty, no C++ code is compiled.
    Value:  /usr/bin/g++

linker (('cvm', 'c|py', 'py', 'c', 'c|py_nogc', 'vm', 'vm_nogc', 'cvm_nogc')) 
    Doc:  Default linker used if the theano flags mode is Mode or ProfileMode(deprecated)
    Value:  cvm

allow_gc (<function booltype at 0x7f951839b6e0>) 
    Doc:  Do we default to delete intermediate results during Theano function calls? Doing so lowers the memory requirement, but asks that we reallocate memory at the next function call. This is implemented for the default linker, but may not work for all linkers.
    Value:  True

optimizer (('fast_run', 'merge', 'fast_compile', 'None')) 
    Doc:  Default optimizer. If not None, will use this linker with the Mode object (not ProfileMode(deprecated) or DebugMode)
    Value:  fast_run

optimizer_verbose (<function booltype at 0x7f951839b8c0>) 
    Doc:  If True, we print all optimization being applied
    Value:  False

on_opt_error (('warn', 'raise', 'pdb', 'ignore')) 
    Doc:  What to do when an optimization crashes: warn and skip it, raise the exception, or fall into the pdb debugger.
    Value:  warn

<theano.configparser.ConfigParam object at 0x7f951839f1d0>
    Doc:  This config option was removed in 0.5: do not use it!
    Value:  True

nocleanup (<function booltype at 0x7f951839bb18>) 
    Doc:  Suppress the deletion of code files that did not compile cleanly
    Value:  False

on_unused_input (('raise', 'warn', 'ignore')) 
    Doc:  What to do if a variable in the 'inputs' list of  theano.function() is not used in the graph.
    Value:  raise

tensor.cmp_sloppy (<type 'int'>) 
    Doc:  Relax tensor._allclose (0) not at all, (1) a bit, (2) more
    Value:  0

tensor.local_elemwise_fusion (<function booltype at 0x7f951839bde8>) 
    Doc:  Enable or not in fast_run mode(fast_run optimization) the elemwise fusion optimization
    Value:  True

gpu.local_elemwise_fusion (<function booltype at 0x7f951839bf50>) 
    Doc:  Enable or not in fast_run mode(fast_run optimization) the gpu elemwise fusion optimization
    Value:  True

lib.amdlibm (<function booltype at 0x7f95183a1140>) 
    Doc:  Use amd's amdlibm numerical library
    Value:  False

gpuelemwise.sync (<function booltype at 0x7f95183a12a8>) 
    Doc:  when true, wait that the gpu fct finished and check it error code.
    Value:  True

traceback.limit (<type 'int'>) 
    Doc:  The number of stack to trace. -1 mean all.
    Value:  7

experimental.mrg (<function booltype at 0x7f95183a1488>) 
    Doc:  Another random number generator that work on the gpu
    Value:  False

experimental.unpickle_gpu_on_cpu (<function booltype at 0x7f95183a15f0>) 
    Doc:  Allow unpickling of pickled CudaNdarrays as numpy.ndarrays.This is useful, if you want to open a CudaNdarray without having cuda installed.If you have cuda installed, this will force unpickling tobe done on the cpu to numpy.ndarray.Please be aware that this may get you access to the data,however, trying to unpicke gpu functions will not succeed.This flag is experimental and may be removed any time, whengpu<>cpu transparency is solved.
    Value:  False

numpy.seterr_all (('ignore', 'warn', 'raise', 'call', 'print', 'log', 'None')) 
    Doc:  ("Sets numpy's behaviour for floating-point errors, ", "see numpy.seterr. 'None' means not to change numpy's default, which can be different for different numpy releases. This flag sets the default behaviour for all kinds of floating-point errors, its effect can be overriden for specific errors by the following flags: seterr_divide, seterr_over, seterr_under and seterr_invalid.")
    Value:  ignore

numpy.seterr_divide (('None', 'ignore', 'warn', 'raise', 'call', 'print', 'log')) 
    Doc:  Sets numpy's behavior for division by zero, see numpy.seterr. 'None' means using the default, defined by numpy.seterr_all.
    Value:  None

numpy.seterr_over (('None', 'ignore', 'warn', 'raise', 'call', 'print', 'log')) 
    Doc:  Sets numpy's behavior for floating-point overflow, see numpy.seterr. 'None' means using the default, defined by numpy.seterr_all.
    Value:  None

numpy.seterr_under (('None', 'ignore', 'warn', 'raise', 'call', 'print', 'log')) 
    Doc:  Sets numpy's behavior for floating-point underflow, see numpy.seterr. 'None' means using the default, defined by numpy.seterr_all.
    Value:  None

numpy.seterr_invalid (('None', 'ignore', 'warn', 'raise', 'call', 'print', 'log')) 
    Doc:  Sets numpy's behavior for invalid floating-point operation, see numpy.seterr. 'None' means using the default, defined by numpy.seterr_all.
    Value:  None

warn.ignore_bug_before (('0.6', 'None', 'all', '0.3', '0.4', '0.4.1', '0.5', '0.7')) 
    Doc:  If 'None', we warn about all Theano bugs found by default. If 'all', we don't warn about Theano bugs found by default. If a version, we print only the warnings relative to Theano bugs found after that version. Warning for specific bugs can be configured with specific [warn] flags.
    Value:  0.6

warn.argmax_pushdown_bug (<function booltype at 0x7f95183a1b18>) 
    Doc:  Warn if in past version of Theano we generated a bug with the theano.tensor.nnet.nnet.local_argmax_pushdown optimization. Was fixed 27 may 2010
    Value:  False

warn.gpusum_01_011_0111_bug (<function booltype at 0x7f95183a1c80>) 
    Doc:  Warn if we are in a case where old version of Theano had a silent bug with GpuSum pattern 01,011 and 0111 when the first dimensions was bigger then 4096. Was fixed 31 may 2010
    Value:  False

warn.sum_sum_bug (<function booltype at 0x7f95183a1de8>) 
    Doc:  Warn if we are in a case where Theano version between version 9923a40c7b7a and the 2 august 2010 (fixed date), generated an error in that case. This happens when there are 2 consecutive sums in the graph, bad code was generated. Was fixed 2 August 2010
    Value:  False

warn.sum_div_dimshuffle_bug (<function booltype at 0x7f95183a1f50>) 
    Doc:  Warn if previous versions of Theano (between rev. 3bd9b789f5e8, 2010-06-16, and cfc6322e5ad4, 2010-08-03) would have given incorrect result. This bug was triggered by sum of division of dimshuffled tensors.
    Value:  False

warn.subtensor_merge_bug (<function booltype at 0x7f95183a7140>) 
    Doc:  Warn if previous versions of Theano (before 0.5rc2) could have given incorrect results when indexing into a subtensor with negative stride (for instance, for instance, x[a:b:-1][c]).
    Value:  False

warn.gpu_set_subtensor1 (<function booltype at 0x7f95183a72a8>) 
    Doc:  Warn if previous versions of Theano (before 0.6) could have given incorrect results when moving to the gpu set_subtensor(x[int vector], new_value)
    Value:  False

warn.vm_gc_bug (<function booltype at 0x7f95183a7410>) 
    Doc:  There was a bug that existed in the default Theano configuration, only in the development version between July 5th 2012 and July 30th 2012. This was not in a released version. If your code was affected by this bug, a warning will be printed during the code execution if you use the `linker=vm,vm.lazy=True,warn.vm_gc_bug=True` Theano flags. This warning is disabled by default as the bug was not released.
    Value:  False

warn.signal_conv2d_interface (<function booltype at 0x7f95183a7578>) 
    Doc:  Warn we use the new signal.conv2d() when its interface changed mid June 2014
    Value:  True

warn.reduce_join (<function booltype at 0x7f95183a76e0>) 
    Doc:  Your current code is fine, but Theano versions prior to 0.7 (or this development version) might have given an incorrect result. To disable this warning, set the Theano flag warn.reduce_join to False. The problem was an optimization, that modified the pattern "Reduce{scalar.op}(Join(axis=0, a, b), axis=0)", did not check the reduction axis. So if the reduction axis was not 0, you got a wrong answer.
    Value:  True

warn.inc_set_subtensor1 (<function booltype at 0x7f95183a7848>) 
    Doc:  Warn if previous versions of Theano (before 0.7) could have given incorrect results for inc_subtensor and set_subtensor when using some patterns of advanced indexing (indexing with one vector or matrix of ints).
    Value:  True

compute_test_value (('off', 'ignore', 'warn', 'raise', 'pdb')) 
    Doc:  If 'True', Theano will run each op at graph build time, using Constants, SharedVariables and the tag 'test_value' as inputs to the function. This helps the user track down problems in the graph before it gets optimized.
    Value:  raise

compute_test_value_opt (('off', 'ignore', 'warn', 'raise', 'pdb')) 
    Doc:  For debugging Theano optimization only. Same as compute_test_value, but is used during Theano optimization
    Value:  off

unpickle_function (<function booltype at 0x7f95183a7aa0>) 
    Doc:  Replace unpickled Theano functions with None. This is useful to unpickle old graphs that pickled them when it shouldn't
    Value:  True

reoptimize_unpickled_function (<function booltype at 0x7f95183a7c08>) 
    Doc:  Re-optimize the graph when a theano function is unpickled from the disk.
    Value:  True

exception_verbosity (('low', 'high')) 
    Doc:  If 'low', the text of exceptions will generally refer to apply nodes with short names such as Elemwise{add_no_inplace}. If 'high', some exceptions will also refer to apply nodes with long descriptions  like:
    A. Elemwise{add_no_inplace}
            B. log_likelihood_v_given_h
            C. log_likelihood_h
    Value:  low

openmp (<function booltype at 0x7f95183a7de8>) 
    Doc:  Allow (or not) parallel computation on the CPU with OpenMP. This is the default value used when creating an Op that supports OpenMP parallelization. It is preferable to define it via the Theano configuration file ~/.theanorc or with the environment variable THEANO_FLAGS. Parallelization is only done for some operations that implement it, and even for operations that implement parallelism, each operation is free to respect this flag or not. You can control the number of threads used with the environment variable OMP_NUM_THREADS. If it is set to 1, we disable openmp in Theano by default.
    Value:  False

openmp_elemwise_minsize (<type 'int'>) 
    Doc:  If OpenMP is enabled, this is the minimum size of vectors for which the openmp parallelization is enabled in element wise ops.
    Value:  200000

check_input (<function booltype at 0x7f95183a9050>) 
    Doc:  Specify if types should check their input in their C code. It can be used to speed up compilation, reduce overhead (particularly for scalars) and reduce the number of generated C files.
    Value:  True

cache_optimizations (<function booltype at 0x7f95183a91b8>) 
    Doc:  WARNING: work in progress, does not work yet. Specify if the optimization cache should be used. This cache will any optimized graph and its optimization. Actually slow downs a lot the first optimization, and could possibly still contains some bugs. Use at your own risks.
    Value:  False

compile.wait (<type 'int'>) 
    Doc:  Time to wait before retrying to aquire the compile lock.
    Value:  5

compile.timeout (<type 'int'>) 
    Doc:  In seconds, time that a process will wait before deciding to
override an existing lock. An override only happens when the existing
lock is held by the same owner *and* has not been 'refreshed' by this
owner for more than this period. Refreshes are done every half timeout
period for running processes.
    Value:  120

compiledir_format (<type 'str'>) 
    Doc:  Format string for platform-dependent compiled module subdirectory
(relative to base_compiledir). Available keys: gxx_version, hostname,
numpy_version, platform, processor, python_bitwidth,
python_int_bitwidth, python_version, short_platform, theano_version.
Defaults to 'compiledir_%(short_platform)s-%(processor)s-%(python_vers
ion)s-%(python_bitwidth)s'.
    Value:  compiledir_%(short_platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s

<theano.configparser.ConfigParam object at 0x7f95182f5250>
    Doc:  platform-independent root directory for compiled modules
    Value:  /home/federico/.theano

<theano.configparser.ConfigParam object at 0x7f95182f5410>
    Doc:  platform-dependent cache directory for compiled modules
    Value:  /home/federico/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.10-64

cmodule.mac_framework_link (<function booltype at 0x7f95182f9488>) 
    Doc:  If set to True, breaks certain MacOS installations with the infamous Bus Error
    Value:  False

cmodule.warn_no_version (<function booltype at 0x7f95182f95f0>) 
    Doc:  If True, will print a warning when compiling one or more Op with C code that can't be cached because there is no c_code_cache_version() function associated to at least one of those Ops.
    Value:  False

cmodule.remove_gxx_opt (<function booltype at 0x7f95182f9758>) 
    Doc:  If True, will remove the -O* parameter passed to g++.This is useful to debug in gdb modules compiled by Theano.The parameter -g is passed by default to g++
    Value:  False

cmodule.compilation_warning (<function booltype at 0x7f95182f98c0>) 
    Doc:  If True, will print compilation warnings.
    Value:  False

cmodule.preload_cache (<function booltype at 0x7f95182f9a28>) 
    Doc:  If set to True, will preload the C module cache at import time
    Value:  False

gcc.cxxflags (<type 'str'>) 
    Doc:  Extra compiler flags for gcc
    Value:  

metaopt.verbose (<function booltype at 0x7f95182d5410>) 
    Doc:  Enable verbose output for meta optimizers
    Value:  False

optdb.position_cutoff (<type 'float'>) 
    Doc:  Where to stop eariler during optimization. It represent the position of the optimizer where to stop.
    Value:  inf

optdb.max_use_ratio (<type 'float'>) 
    Doc:  A ratio that prevent infinite loop in EquilibriumOptimizer.
    Value:  5.0

profile (<function booltype at 0x7f9518277d70>) 
    Doc:  If VM should collect profile information
    Value:  False

profile_optimizer (<function booltype at 0x7f9518277ed8>) 
    Doc:  If VM should collect optimizer profile information
    Value:  False

profile_memory (<function booltype at 0x7f951821b0c8>) 
    Doc:  If VM should collect memory profile information and print it
    Value:  False

<theano.configparser.ConfigParam object at 0x7f9518218310>
    Doc:  Useful only for the vm linkers. When lazy is None, auto detect if lazy evaluation is needed and use the apropriate version. If lazy is True/False, force the version used between Loop/LoopGC and Stack.
    Value:  None

optimizer_excluding (<type 'str'>) 
    Doc:  When using the default mode, we will remove optimizer with these tags. Separate tags with ':'.
    Value:  

optimizer_including (<type 'str'>) 
    Doc:  When using the default mode, we will add optimizer with these tags. Separate tags with ':'.
    Value:  

optimizer_requiring (<type 'str'>) 
    Doc:  When using the default mode, we will require optimizer with these tags. Separate tags with ':'.
    Value:  

DebugMode.patience (<type 'int'>) 
    Doc:  Optimize graph this many times to detect inconsistency
    Value:  10

DebugMode.check_c (<function booltype at 0x7f951823ded8>) 
    Doc:  Run C implementations where possible
    Value:  True

DebugMode.check_py (<function booltype at 0x7f95182520c8>) 
    Doc:  Run Python implementations where possible
    Value:  True

DebugMode.check_finite (<function booltype at 0x7f9518252230>) 
    Doc:  True -> complain about NaN/Inf results
    Value:  True

DebugMode.check_strides (<type 'int'>) 
    Doc:  Check that Python- and C-produced ndarrays have same strides. On difference: (0) - ignore, (1) warn, or (2) raise error
    Value:  0

DebugMode.warn_input_not_reused (<function booltype at 0x7f9518252488>) 
    Doc:  Generate a warning when destroy_map or view_map says that an op works inplace, but the op did not reuse the input for its output.
    Value:  True

DebugMode.check_preallocated_output (<type 'str'>) 
    Doc:  Test thunks with pre-allocated memory as output storage. This is a list of strings separated by ":". Valid values are: "initial" (initial storage in storage map, happens with Scan),"previous" (previously-returned memory), "c_contiguous", "f_contiguous", "strided" (positive and negative strides), "wrong_size" (larger and smaller dimensions), and "ALL" (all of the above).
    Value:  

DebugMode.check_preallocated_output_ndim (<type 'int'>) 
    Doc:  When testing with "strided" preallocated output memory, test all combinations of strides over that number of (inner-most) dimensions. You may want to reduce that number to reduce memory or time usage, but it is advised to keep a minimum of 2.
    Value:  4

profiling.time_thunks (<function booltype at 0x7f9517fd5938>) 
    Doc:  Time individual thunks when profiling
    Value:  True

profiling.n_apply (<type 'int'>) 
    Doc:  Number of Apply instances to print by default
    Value:  20

profiling.n_ops (<type 'int'>) 
    Doc:  Number of Ops to print by default
    Value:  20

profiling.output_line_width (<type 'int'>) 
    Doc:  Max line width for the profiling output
    Value:  512

profiling.min_memory_size (<type 'int'>) 
    Doc:  For the memory profile, do not print Apply nodes if the size
             of their outputs (in bytes) is lower than this threshold
    Value:  1024

profiling.min_peak_memory (<function booltype at 0x7f9517fd5e60>) 
    Doc:  The min peak memory usage of the order
    Value:  False

profiling.destination (<type 'str'>) 
    Doc:  
             File destination of the profiling output
             
    Value:  stderr

ProfileMode.n_apply_to_print (<type 'int'>) 
    Doc:  Number of apply instances to print by default
    Value:  15

ProfileMode.n_ops_to_print (<type 'int'>) 
    Doc:  Number of ops to print by default
    Value:  20

ProfileMode.min_memory_size (<type 'int'>) 
    Doc:  For the memory profile, do not print apply nodes if the size of their outputs (in bytes) is lower then this threshold
    Value:  1024

ProfileMode.profile_memory (<function booltype at 0x7f9517fee050>) 
    Doc:  Enable profiling of memory used by Theano functions
    Value:  False

on_shape_error (('warn', 'raise')) 
    Doc:  warn: print a warning and use the default value. raise: raise an error
    Value:  warn

tensor.insert_inplace_optimizer_validate_nb (<type 'int'>) 
    Doc:  -1: auto, if graph have less then 500 nodes 1, else 10
    Value:  -1

experimental.local_alloc_elemwise (<function booltype at 0x7f9517be99b0>) 
    Doc:  DEPRECATED: If True, enable the experimental optimization local_alloc_elemwise. Generates error if not True. Use optimizer_excluding=local_alloc_elemwise to dsiable.
    Value:  True

experimental.local_alloc_elemwise_assert (<function booltype at 0x7f9517be9a28>) 
    Doc:  When the local_alloc_elemwise is applied, add an assert to highlight shape errors.
    Value:  True

blas.ldflags (<type 'str'>) 
    Doc:  lib[s] to include for [Fortran] level-3 blas implementation
    Value:  -L/opt/OpenBLAS/lib -lopenblas -lopenblas

warn.identify_1pexp_bug (<function booltype at 0x7f9516dcc848>) 
    Doc:  Warn if Theano versions prior to 7987b51 (2011-12-18) could have yielded a wrong result due to a bug in the is_1pexp function
    Value:  False

scan.allow_gc (<function booltype at 0x7f9515c44050>) 
    Doc:  Allow/disallow gc inside of Scan (default: False)
    Value:  False

scan.allow_output_prealloc (<function booltype at 0x7f9515c44d70>) 
    Doc:  Allow/disallow memory preallocation for outputs inside of scan (default: True)
    Value:  True

unittests.rseed (<type 'str'>) 
    Doc:  Seed to use for randomized unit tests. Special value 'random' means using a seed of None.
    Value:  666

nvcc.compiler_bindir (<type 'str'>) 
    Doc:  If defined, nvcc compiler driver will seek g++ and gcc in this directory
    Value:  

cuda.root (<type 'str'>) 
    Doc:  directory with bin/, lib/, include/ for cuda utilities.
        This directory is included via -L and -rpath when linking
        dynamically compiled modules.  If AUTO and nvcc is in the
        path, it will use one of nvcc parent directory.  Otherwise
        /usr/local/cuda will be used.  Leave empty to prevent extra
        linker directives.  Default: environment variable "CUDA_ROOT"
        or else "AUTO".
        
    Value:  None

<theano.configparser.ConfigParam object at 0x7f9504bf6550>
    Doc:  Extra compiler flags for nvcc
    Value:  

nvcc.fastmath (<function booltype at 0x7f9504be8e60>) 
    Doc:  
    Value:  False

pycuda.init (<function booltype at 0x7f9504bfb1b8>) 
    Doc:  If True, always initialize PyCUDA when Theano want to
           initilize the GPU.  Currently, we must always initialize
           PyCUDA before Theano do it.  Setting this flag to True,
           ensure that, but always import PyCUDA.  It can be done
           manually by importing theano.misc.pycuda_init before theano
           initialize the GPU device.
             
    Value:  False

cublas.lib (<type 'str'>) 
    Doc:  Name of the cuda blas library for the linker.
    Value:  cublas

gpuarray.sync (<function booltype at 0x7f9504c07a28>) 
    Doc:  If True, every op will make sure its work is done before
                returning.  Setting this to True will slow down execution,
                but give much more accurate results in profiling.
    Value:  False
```

Again - using bleeding edge numpy (build from source), scipy (built from source) and linked against openblas.  I'm happy to keep trouble shooting if it helps.

**Comment by nouiz** [comment]
I have looked at the code related to this and don't understand how this can happen. Can you give me a script that reproduce this and tell me the needed dependency?

I need to see the code working to find a fix.

**Comment by FedericoV** [comment]
This is just calling Theano through PyMC3.  I will try to narrow it down as
much as possible tomorrow so I can have a minimal working example.

On Mon, Jul 20, 2015 at 10:13 PM, Frédéric Bastien <notifications@github.com

**Comment by FedericoV** [comment]
Since #2870 reported the same issue, I tried running his code, to see if I obtained the same error, and I do:

```

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7fb40370dd90>
ERROR:theano.gof.opt:SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7fb40370dd90>
ERROR (theano.gof.opt): Traceback:
ERROR:theano.gof.opt:Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 194, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 79, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5788, in apply
    new_outputs = self.optimizer(node)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5735, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5735, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5735, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5735, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5735, in local_fuse
    ret = local_fuse(n)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5723, in local_fuse
    n = maker(node, C)(*inputs).owner
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/opt.py", line 5536, in maker
    return OP(scalar_op)
  File "/home/federico/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/elemwise.py", line 504, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 35 and outputs = 1)
```

This is using the full example from #2870.  He mentioned that he fixed the error by reinstalling numpy - so I'll try to do that to see if that fixes things.  Maybe it's something related to the very latest version of numpy, because I'm currently using the bleeding edge version built from their repo?  I'll try using the 1.9* branch instead, and see if that helps.

**Comment by FedericoV** [comment]
EUREKA:

Ok, I downloaded numpy, rebuilt the 1.9.2 branch, then rebuilt scipy, and now Theano no longer seems to give that error.  Annoying, it seems like there was an ABI change so everything that was linked against the newer numpy had to be rebuilt.

I *strongly* suspect the error is related to the ABI changes happening in numpy.

**Comment by nouiz** [comment]
which version of numpy cause you problems?

**Comment by FedericoV** [comment]
The very last bleeding edge one - built from the repo.  When I switched to
1.9.2, everything was fine.  I also had to rebuild scipy, scikit-learn,
pandas, etc because apparently there was an incompatible ABI change between
the two versions.

**Comment by jameskyle** [comment]
I'm getting this error running the theano test suite

numpy==1.10.0
scipy==0.16.0
Theano==0.7.0

**Comment by cwerner87** [comment]
I get this error when upgrading to numpy 1.10. I reverted to 1.9.3 and I no longer get it.

**Comment by neocxi** [comment]
Also have the same error with numpy 1.10.0

**Comment by twiecki** [comment]
Same problem with 1.10.0.

**Comment by linfengzhou** [comment]
Same Problem here
python 2.7.10
numpy 1.10.0

**Comment by nouiz** [comment]
Can one of you give me a full script that generate this problem? It can
depend on pymc, the code snippet there do not seem enough to generate it
and I don't know enough pymc3 to guess easily what is missing.

I have an idea of how to fix it, but I would like to test my fix first.

**Comment by linfengzhou** [comment]
Please check this ipython notebook , thank you ! 
https://github.com/linfengzhou/Applied_Data_Science/blob/master/Assignment%205/Homework%205.ipynb

**Comment by abergeron** [comment]
I have also encountered this problem and like everybody says this is a new limitation in numpy 1.10.

To fix it we can either

disable the pre-building of the ufunc in \__init__ and \__setstate__
https://github.com/Theano/Theano/blob/master/theano/tensor/elemwise.py#L509
https://github.com/Theano/Theano/blob/master/theano/tensor/elemwise.py#L531

or 

limit the number of inputs to 32 instead of the current 1024.
https://github.com/Theano/Theano/blob/master/theano/tensor/opt.py#L6320

The second option will still break for cached ops that have more than 32 inputs though.

**Comment by nouiz** [comment]
The current limit is 32, not 1024. We already lowered this in the past. I think at one place in the optimization I don't do correctly the cont before fusing node in some cases.

I'm able to reproduce it. thanks.

**Comment by nouiz** [comment]
I have a PR gh-3532. thanks for the code to reproduce it.

**Comment by dmoccia** [comment]
Hello

I can see this thread is a bit old and looks like you put a fix in October, but I am seeing a similar error after downloading and installing Theano today when I run the nosetests.   I am using openBlas (0.2.15) and numpy 1.10.4.  Not sure if I should simply roll back from numpy to 1.9.3 as others did in the past?  

Thanks for any clarification
```

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x109e54510>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/dennis/miniconda3/envs/theanoLearn/lib/python2.7/site-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/Users/dennis/miniconda3/envs/theanoLearn/lib/python2.7/site-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/Users/dennis/miniconda3/envs/theanoLearn/lib/python2.7/site-packages/theano/tensor/opt.py", line 5498, in apply
    new_outputs = self.optimizer(node)
  File "/Users/dennis/miniconda3/envs/theanoLearn/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/Users/dennis/miniconda3/envs/theanoLearn/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/Users/dennis/miniconda3/envs/theanoLearn/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/Users/dennis/miniconda3/envs/theanoLearn/lib/python2.7/site-packages/theano/tensor/opt.py", line 5433, in local_fuse
    n = OP(C)(*inputs).owner
  File "/Users/dennis/miniconda3/envs/theanoLearn/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 496, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 33 and outputs = 1)
```

**Comment by FedericoV** [comment]
Try building theano from source.  Old theano versions still suffer from
this bug sometime.

**Comment by dmoccia** [comment]
Thanks Federico, I will try that out and report back.  I forget to mention I installed Theano via pip but you figured that out!

**Comment by dmoccia** [comment]
Yup that did it!  Thank you again for the quick reply

**Comment by nmclay** [comment]
I've been getting this error as well.  I'm running python 3.5.1 in a virtual environment, Numpy version 1.10.4.  I created a new virtual environment with just python, numpy, scipy and theano.  When I run theano.test() in this environment I get the same error shown in the output.

**Comment by nouiz** [comment]
Use Theano 0.8rc1 or the development version:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions
