### ISSUE TITLE
gpu illegal memory access

### ISSUE THREAD

**Issue by zcyang** [Theano/Theano#3084]
Hi,

I meet with this problem when I am using theano for a project 
```shell
2015-06-29T02:52:42.784295] iteration 0/368650 cost 285.914001 length 14
2015-06-29T02:56:07.923116] validation cost: 298.046211
13
(10, 4096)
2015-06-29T02:56:09.599871] iteration 1/368650 cost 300.855438 length 13
12
(10, 4096)
Error when tring to find the memory information on the GPU: an illegal memory access was encountered
Error freeing device pointer 0xb047d3800 (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total
Error when tring to find the memory information on the GPU: an illegal memory access was encountered
Error freeing device pointer 0xb15e1e000 (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total
device_free: cudaFree() returned an error, but there is already an Python error set. This happen during the clean up when there is a first error and the CUDA driver is in a so bad state that it don't work anymore. We keep the previous error set to help debugging it.CudaNdarray_uninit: error freeing self->devdata. (self=0x20e35230, self->devata=0xb15e1e000)
Error when trying to find the memory information on the GPU: an illegal memory access was encountered
Error allocating 16777216 bytes of device memory (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total
Traceback (most recent call last):
  File "image_qa.py", line 141, in <module>
    label_idx, label_mask, label)
  File "/home/zichaoy/local/lib/python2.6/site-packages/Theano-0.7.0-py2.6.egg/theano/compile/function_module.py", line 608, in __call__
    storage_map=self.fn.storage_map)
  File "/home/zichaoy/local/lib/python2.6/site-packages/Theano-0.7.0-py2.6.egg/theano/compile/function_module.py", line 597, in __call__
    outputs = self.fn()
MemoryError: Error allocating 16777216 bytes of device memory (an illegal memory access was encountered).
Apply node that caused the error: GpuElemwise{mul,no_inplace}(CudaNdarrayConstant{error while transferring the value: error copying data to host}, GpuDimShuffle{x,x}.0, image_hidden_w)
Inputs types: [CudaNdarrayType(float32, (True, True)), CudaNdarrayType(float32, (True, True)), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(1, 1), (1, 1), (4096, 1024)]
Inputs strides: [(0, 0), (0, 0), (1024, 1)]
Inputs values: [<CudaNdarray object at 0x17a8c2f0>, <CudaNdarray object at 0x20e40e70>, 'not shown']
```

I am using k40 and I am sure that the memory is enough. I tried it on other types of gpus as well, the same problem occurs and it is deterministic. I have been using theano for several other projects and everything works out fine. 

I found other reports similar problems [here](https://groups.google.com/forum/#!msg/theano-users/Pu4YKlZKwm4/E7RdNHioXyoJ), however it seems no solution is provided. I have tried out all suggestion there as well, the error remains.

Can it be a potential bug of theano?

**Comment by nouiz** [comment]
Which version of cuda do you use?

This could be caused by old cublas version. Update to cuda 7.0. This fixed
some errors like this.

If you want to be sure that this happen in cublas before the update, run
again with this env variable:

CUDA_LAUNCH_BLOCKING=1 and give me the new output.

**Comment by zcyang** [comment]
Thanks for the reply!

I have tried and `CUDA_LAUNCH_BLOCKING=1` does not change anything for the output.

I am using cuda6.5, is this a problem of cuda 6.5? I will try cuda 7 out?

**Comment by nouiz** [comment]
I check the an old note about this and it was cuda 5.5 and 6.0 with some
GPUs including your that had problems. 6.5 was fixing the problems we saw.

I would be surprised that this is a bug in Theano, but this is possible.

Can you try with smaller data, just to be sure you really have enough
memory?

You told that the error is the same. Are you sure there isn't 1 line that
changed? The output is big, so missing one line change is easy.

**Comment by zcyang** [comment]
Confirmed that exactly the same error appears with `CUDA_LAUNCH_BLOCKING=1`, expect the address is not the same `Error freeing device pointer xxxx `, if this matters.

Changed the batch size from 100, to 10 and 2, the problem still exists, I am sure memory is enough, K40 has 12G and I only use about 1G.

**Comment by zcyang** [comment]
the strange point is that 
`MemoryError: Error allocating 16777216 bytes of device memory (an illegal memory access was encountered).
Apply node that caused the error: GpuElemwise{mul,no_inplace}(CudaNdarrayConstant{error while transferring the value: error copying data to host}, GpuDimShuffle{x,x}.0, image_hidden_w)
Inputs types: [CudaNdarrayType(float32, (True, True)), CudaNdarrayType(float32, (True, True)), CudaNdarrayType(float32, matrix)]
`
The matrix try to allocate is a shared variable and has been used several times before the error appears

**Comment by zcyang** [comment]
It seems I fixed the problem.

I change the matrix indexing from -1 to len(matrix) -1 and the problem disappears, but theano support negative indexing... not sure why...

**Comment by nouiz** [comment]
Just to be sure, with the negative indexing and CUDA_LAUNCH_BLOCKING=1
didn't change that line in the output:

Apply node that caused the error:
GpuElemwise{mul,no_inplace}(CudaNdarrayConstant{error while

Can you update to Theano dev and train with the neg indexing? We fixed a
place where this wasn't working well on the GPU.

If that do not fix it, can you tell me how the indexing was done with the
neg indexing, to try to see where this could come from.

**Comment by nouiz** [comment]
I did a PR that add support for negative indexing on the GPU. thanks for the report.

**Comment by cheolho** [comment]
I met the similar error.

> Error when tring to find the memory information on the GPU: an illegal memory access was encountered
> Error freeing device pointer 0xb4fd40000 (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total
> CudaNdarray_uninit: error freeing self->devdata. (self=0x7f3aacbd2db0, self->devata=0xb4fd40000)

`nvcc --version` gives
> Cuda compilation tools, release 7.5, V7.5.17

`nvidia-smi` gives

> Memory-Usage: 2375MiB / 6143MiB

Storage map footprint in the error message gives

>  TotalSize: 436727159.0 Byte(s) 0.407 GB
>  TotalSize inputs: 409703551.0 Byte(s) 0.382 GB

Could you give me any idea to solve this problem?

**Comment by morningsky** [comment]
@cheolho  @zcyang  I have meet the same problems too, Have you solve this problem? Who can give me some guides? Thanks!

**Comment by nouiz** [comment]
I fixed one such error recently. Update to Theano dev version:

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

If that don't fix it, run it again with the env variable:
CUDA_LAUNCH_BLOCKING=1

and give me the full error.

**Comment by morningsky** [comment]
@nouiz  I am very glad to have your reply. I have update the theano dev version. But I also meet the error.  For help! Thanks!

> Using Theano backend.
> Couldn't import dot_parser, loading of dot files will not be possible.
> Using gpu device 0: GeForce GTX 970 (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 3007.)
> /root/anaconda2/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/models.py:325: UserWarning: "class_mode" argument is deprecated, please remove it.
>   warnings.warn('"class_mode" argument is deprecated, '
> Train on 916 samples, validate on 230 samples
> Epoch 1/100
> Error allocating 528515072 bytes of device memory (out of memory). Driver report 483991552 bytes free and 4291493888 bytes total 
> Traceback (most recent call last):
>   File "vgg.py", line 127, in <module>
>     model.fit(train_data,train_label,batch_size=128,nb_epoch=100,shuffle=True,verbose=1,validation_split=0.2)
>   File "/root/anaconda2/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/models.py", line 402, in fit
>     sample_weight=sample_weight)
>   File "/root/anaconda2/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/engine/training.py", line 1040, in fit
>     callback_metrics=callback_metrics)
>   File "/root/anaconda2/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/engine/training.py", line 778, in _fit_loop
>     outs = f(ins_batch)
>   File "/root/anaconda2/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/backend/theano_backend.py", line 499, in __call__
>     return self.function(*inputs)
>   File "/root/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 902, in __call__
>     storage_map=getattr(self.fn, 'storage_map', None))
>   File "/root/anaconda2/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
>     reraise(exc_type, exc_value, exc_trace)
>   File "/root/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 889, in __call__
>     self.fn() if output_subset is None else\
> MemoryError: Error allocating 528515072 bytes of device memory (out of memory).
> Apply node that caused the error: GpuAlloc{memset_0=True}(CudaNdarrayConstant{0.0}, Shape_i{0}.0, TensorConstant{64}, Elemwise{add,no_inplace}.0, Elemwise{add,no_inplace}.0)
> Toposort index: 125
> Inputs types: [CudaNdarrayType(float32, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar)]
> Inputs shapes: [(), (), (), (), ()]
> Inputs strides: [(), (), (), (), ()]
> Inputs values: [CudaNdarray(0.0), array(128), array(64), array(127), array(127)]
> Outputs clients: [[GpuIncSubtensor{InplaceSet;::, ::, int64:int64:, int64:int64:}(GpuAlloc{memset_0=True}.0, GpuDownsampleFactorMax{(2, 2),True}.0, Constant{1}, ScalarFromTensor.0, Constant{1}, ScalarFromTensor.0)]]
> 
> HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
> HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storag

**Comment by cheolho** [comment]
@morningsky For me, I think it was the problem of memory depletion. (not enough memory!) The array was too large.
