### ISSUE TITLE
Not able to use GPU

### ISSUE THREAD

**Issue by TeunKrikke** [Theano/Theano#3629]
Hi,

After I successfully installed Theano and LibGPUArray and pyGPU on a Ubuntu 14.04 machine with a 4 NVIDIA Titan X cards with CUDA 7.5 and NVIDIA 352 drivers 

I wanted to run the check1.py file with the following command:
```
THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32 python check1.py
```
but this gave the following error 
```
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: Unable to get the number of gpus available: unknown error)
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 2.364756 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu
```
So I tried running it like this with the assumption that I was perhaps not using the libgpuarry or pygpu
```
THEANO_FLAGS=mode=FAST_RUN,device=cuda,floatX=float32 python check1.py
```
However the outcome was this:
```
ERROR (theano.sandbox.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/gpuarray/__init__.py", line 65, in <module>
    init_dev(config.device)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/gpuarray/__init__.py", line 49, in init_dev
    init_dev.devmap[dev] = pygpu.init(dev)
  File "pygpu/gpuarray.pyx", line 605, in pygpu.gpuarray.init (pygpu/gpuarray.c:8352)
  File "pygpu/gpuarray.pyx", line 576, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8281)
  File "pygpu/gpuarray.pyx", line 981, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12083)
GpuArrayException: API not initialized
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
```
Running it with cuda0 instead of cuda gave me the following error message 
```
ERROR (theano.sandbox.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/gpuarray/__init__.py", line 65, in <module>
    init_dev(config.device)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/gpuarray/__init__.py", line 49, in init_dev
    init_dev.devmap[dev] = pygpu.init(dev)
  File "pygpu/gpuarray.pyx", line 605, in pygpu.gpuarray.init (pygpu/gpuarray.c:8352)
  File "pygpu/gpuarray.pyx", line 576, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8281)
  File "pygpu/gpuarray.pyx", line 981, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12083)
GpuArrayException: Unknown internal error
```

Can you please help me

**Comment by nouiz** [comment]
Use device=gpu0

If that work, try device=cuda0

To be sure you need to reboot after installing the driver.

Fred

**Comment by TeunKrikke** [comment]
Thanks for your quick response

Rebooted the machine. After that tried 
``` 
THEANO_FLAGS=device=gpu0 python check1.py
```
Which gives :
```
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu0 is not available  (error: Unable to get the number of gpus available: unknown error)
```

and tried 
``` 
THEANO_FLAGS=device=cuda0 python check1.py
```

with this result:
```
ERROR (theano.sandbox.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/gpuarray/__init__.py", line 65, in <module>
    init_dev(config.device)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/gpuarray/__init__.py", line 49, in init_dev
    init_dev.devmap[dev] = pygpu.init(dev)
  File "pygpu/gpuarray.pyx", line 605, in pygpu.gpuarray.init (pygpu/gpuarray.c:8352)
  File "pygpu/gpuarray.pyx", line 576, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8281)
  File "pygpu/gpuarray.pyx", line 981, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12083)
GpuArrayException: unknown error
```
Running 
```
python -c "import pygpu;pygpu.test()"
```

Gives me six times the same error:

```
ERROR: Failure: GpuArrayException (Unknown error)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/test_tools.py", line 5, in <module>
    from .support import (guard_devsup, rand, check_flags, check_meta, check_all,
  File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/support.py", line 32, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu/gpuarray.pyx", line 605, in pygpu.gpuarray.init (pygpu/gpuarray.c:8352)
  File "pygpu/gpuarray.pyx", line 576, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8281)
  File "pygpu/gpuarray.pyx", line 981, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12083)
GpuArrayException: Unknown error
```

**Comment by nouiz** [comment]
There is a problem with the way your computer is configured.

Is the nvidia driver running? Maybe not. Can you execute nvidia-smi on the
command line?

Maybe reinstalling nvidia driver will help.

**Comment by TeunKrikke** [comment]
Yes this is the outcome:

```
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:02:00.0      On |                  N/A |
| 22%   39C    P8    16W / 250W |    216MiB / 12285MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:03:00.0     Off |                  N/A |
| 22%   43C    P8    16W / 250W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:82:00.0     Off |                  N/A |
| 22%   43C    P8    17W / 250W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 0000:83:00.0     Off |                  N/A |
| 22%   41C    P8    16W / 250W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1997    G   /usr/bin/X                                     192MiB |
+-----------------------------------------------------------------------------+
```

**Comment by TeunKrikke** [comment]
Reinstalled the gpu driver but it gave the same result

**Comment by nouiz** [comment]
Try to run nvidia samples in the sdk. If they don't work, Theano can't work.

Did you install the cuda sdk that have nvcc? I suppose so.

**Comment by TeunKrikke** [comment]
Hi,

I have reinstalled the cuda 7.5 toolkit and used the included display driver. Before I used the apt-get display driver but that seemed to be the source of all the trouble. It works now with cuda0 and gpu 0 as parameters.

Thanks for all you help!!!

**Comment by muthiyanbhushan** [comment]
Hello @TeunKrikke,

Can you please elaborate the work which you did to work gpu 0.

I am getting same error on EC2 p2.2 large instance.

I have cuda-8 installed.

nvidia-smi gives me ouptut.

nvidia-smi
Wed Jun 28 18:45:13 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:00:0F.0     Off |                    0 |
| N/A   48C    P8    28W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000:00:10.0     Off |                    0 |
| N/A   40C    P8    31W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 0000:00:11.0     Off |                    0 |
| N/A   58C    P8    30W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 0000:00:12.0     Off |                    0 |
| N/A   48C    P8    31W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           Off  | 0000:00:13.0     Off |                    0 |
| N/A   52C    P8    57W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla K80           Off  | 0000:00:14.0     Off |                    0 |
| N/A   43C    P0    69W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla K80           Off  | 0000:00:15.0     Off |                    0 |
| N/A   52C    P0    56W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla K80           Off  | 0000:00:16.0     Off |                    0 |
| N/A   45C    P0    69W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   8  Tesla K80           Off  | 0000:00:17.0     Off |                    0 |
| N/A   48C    P0    55W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   9  Tesla K80           Off  | 0000:00:18.0     Off |                    0 |
| N/A   41C    P0    69W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|  10  Tesla K80           Off  | 0000:00:19.0     Off |                    0 |
| N/A   49C    P0    61W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|  11  Tesla K80           Off  | 0000:00:1A.0     Off |                    0 |
| N/A   44C    P0    71W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|  12  Tesla K80           Off  | 0000:00:1B.0     Off |                    0 |
| N/A   46C    P0    57W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|  13  Tesla K80           Off  | 0000:00:1C.0     Off |                    0 |
| N/A   43C    P0    69W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|  14  Tesla K80           Off  | 0000:00:1D.0     Off |                    0 |
| N/A   49C    P0    57W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|  15  Tesla K80           Off  | 0000:00:1E.0     Off |                    0 |
| N/A   44C    P0    68W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

nvcc --version give me cuda version 8.0 installed.

But I am getting below warning:


modprobe: ERROR: could not insert 'nvidia_375_uvm': Invalid argument
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be red in the next release (v0.10).  Please switch to the gpuarray backend. You cet more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28rray%29

WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu 0 is not avble  (error: Unable to get the number of gpus available: unknown error)
Using Theano backend.



Thank you for your help.

Regards,
Bhushan

**Comment by nouiz** [comment]
this is a problem with the driver. Did you started the VM from a VM with
cuda and the driver installed? If not, I would recommand to start from such
working VM.

**Comment by TeunKrikke** [comment]
@muthiyanbhushan Given it is a vm I don't know if you have rights to do anything with the driver. In my case it was reinstalling the driver and removing apt-get version at the time. Since then I have not updated it regulary and have adopted the if it isn't broken than don't fix it style :).

The easiest option in your case would be to follow @nouiz's advice.

The more difficult option would involve installing cuda and using the display driver that it provides but I am not sure if that is possible because I have not worked with that VM.

**Comment by mahdiheybati73** [comment]
hi 
i have 1060 gtx gpu and cuda v8 with cudnn 5.1 is installed. 
i have theano 0.8.2
 i got this error. 

EnvironmentError: ('The following error happened while compiling the node', GpuFromHost(Elemwise{exp,no_inplace}.0), '\n', 'You forced the use of gpu device gpu, but CUDA initialization failed with error:\ncuda unavailable')

**Comment by mahdiheybati73** [comment]
how can i fix this issue??

**Comment by nouiz** [comment]
Do not re-activate old issue for non-related problems. We do not support that version of Theano anymore. I would suggest that you try the latest version or find another framework (see https://groups.google.com/forum/#!msg/theano-users/7Poq8BZutbY/rNCIfvAEAwAJ)
