### ISSUE TITLE
Pool 2D optimization

### ISSUE THREAD

**Issue by albertomontesg** [Theano/Theano#4377]
Hi all, 

I'm training a quite large network using theano and this network starts with a 3D convolution layer and then a 3D Max Pool Layer. The network I talk about can be found [here](https://gist.github.com/albertomontesg/d8b21a179c1e6cca0480ebdf292c34d2). For training it I'm using Keras which allows very easily to do 3D convolution layers, but for 3D max pooling layers it makes 2 operation of max pooling over the different dimensions. Here is the implementation in Keras to do 3D pooling:
```python
        # pooling over conv_dim2, conv_dim1 (last two channels)
        output = pool.pool_2d(input=x.dimshuffle(0, 1, 4, 3, 2),
                              ds=(pool_size[1], pool_size[0]),
                              st=(strides[1], strides[0]),
                              ignore_border=ignore_border,
                              padding=padding,
                              mode='max')

        # pooling over conv_dim3
        pool_out = pool.pool_2d(input=output.dimshuffle(0, 1, 4, 3, 2),
                                ds=(1, pool_size[2]),
                                st=(1, strides[2]),
                                ignore_border=ignore_border,
                                padding=padding,
                                mode='max')
```

So trying to train my network I found the following weird error:
```
RuntimeError: GpuDnnPool: error doing cudnnPoolingForward operation: CUDNN_STATUS_EXECUTION_FAILED
Apply node that caused the error: GpuDnnPool{mode='max'}(GpuContiguous.0, TensorConstant{[2 1]}, TensorConstant{[2 1]}, TensorConstant{(2,) of 0})
Toposort index: 503
Inputs types: [CudaNdarrayType(float32, (False, True, False, False)), TensorType(int64, vector), TensorType(int64, vector), TensorType(int64, vector)]
Inputs shapes: [(114688, 1, 112, 16), (2,), (2,), (2,)]
Inputs strides: [(1792, 0, 16, 1), (8,), (8,), (8,)]
Inputs values: ['not shown', array([2, 1]), array([2, 1]), array([0, 0])]
Outputs clients: [[GpuReshape{5}(GpuDnnPool{mode='max'}.0, Join.0), GpuContiguous(GpuDnnPool{mode='max'}.0)]]

Debugprint of the apply node:
GpuDnnPool{mode='max'} [id A] <CudaNdarrayType(float32, (False, True, False, False))> ''
 |GpuContiguous [id B] <CudaNdarrayType(float32, (False, True, False, False))> ''
 | |GpuReshape{4} [id C] <CudaNdarrayType(float32, (False, True, False, False))> ''
 |   |GpuDimShuffle{0,1,4,3,2} [id D] <CudaNdarrayType(float32, 5D)> ''
 |   | |GpuElemwise{mul,no_inplace} [id E] <CudaNdarrayType(float32, 5D)> ''
 |   |   |CudaNdarrayConstant{[[[[[ 0.5]]]]]} [id F] <CudaNdarrayType(float32, (True, True, True, True, True))>
 |   |   |GpuElemwise{add,no_inplace} [id G] <CudaNdarrayType(float32, 5D)> ''
 |   |     |GpuElemwise{add,no_inplace} [id H] <CudaNdarrayType(float32, 5D)> ''
 |   |     | |GpuDimShuffle{0,2,1,3,4} [id I] <CudaNdarrayType(float32, 5D)> ''
 |   |     | | |GpuReshape{5} [id J] <CudaNdarrayType(float32, 5D)> ''
 |   |     | |   |GpuCAReduce{add}{0,1,0} [id K] <CudaNdarrayType(float32, matrix)> ''
 |   |     | |   | |GpuReshape{3} [id L] <CudaNdarrayType(float32, 3D)> ''
 |   |     | |   |   |DiagonalSubtensor [id M] <CudaNdarrayType(float32, 6D)> ''
 |   |     | |   |   | |GpuReshape{6} [id N] <CudaNdarrayType(float32, 6D)> ''
 |   |     | |   |   | | |GpuDnnConv{algo='small', inplace=True} [id O] <CudaNdarrayType(float32, 4D)> ''
 |   |     | |   |   | | | |GpuContiguous [id P] <CudaNdarrayType(float32, 4D)> ''
 |   |     | |   |   | | | | |GpuReshape{4} [id Q] <CudaNdarrayType(float32, 4D)> ''
 |   |     | |   |   | | | |   |GpuDimShuffle{0,2,1,3,4} [id R] <CudaNdarrayType(float32, 5D)> ''
 |   |     | |   |   | | | |   | |GpuIncSubtensor{Set;::, ::, int64:int64:, int64:int64:, int64:int64:} [id S] <CudaNdarrayType(float32, 5D)> ''
 |   |     | |   |   | | | |   |   |GpuAlloc{memset_0=True} [id T] <CudaNdarrayType(float32, 5D)> ''
 |   |     | |   |   | | | |   |   | |CudaNdarrayConstant{0.0} [id U] <CudaNdarrayType(float32, scalar)>
 |   |     | |   |   | | | |   |   | |Subtensor{int64} [id V] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   | | |GpuShape [id W] <TensorType(int64, vector)> ''
 |   |     | |   |   | | | |   |   | | | |GpuFromHost [id X] <CudaNdarrayType(float32, 5D)> ''
 |   |     | |   |   | | | |   |   | | |   |convolution3d_input_1 [id Y] <TensorType(float32, 5D)>
 |   |     | |   |   | | | |   |   | | |Constant{0} [id Z] <int64>
 |   |     | |   |   | | | |   |   | |Subtensor{int64} [id BA] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   | | |GpuShape [id W] <TensorType(int64, vector)> ''
 |   |     | |   |   | | | |   |   | | |Constant{1} [id BB] <int64>
 |   |     | |   |   | | | |   |   | |Elemwise{add,no_inplace} [id BC] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   | | |Subtensor{int64} [id BD] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   | | | |GpuShape [id W] <TensorType(int64, vector)> ''
 |   |     | |   |   | | | |   |   | | | |Constant{2} [id BE] <int64>
 |   |     | |   |   | | | |   |   | | |Elemwise{sub,no_inplace} [id BF] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   | |   |Shape_i{2} [id BG] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   | |   | |conv1_W [id BH] <CudaNdarrayType(float32, 5D)>
 |   |     | |   |   | | | |   |   | |   |TensorConstant{1} [id BI] <TensorType(int8, scalar)>
 |   |     | |   |   | | | |   |   | |Elemwise{add,no_inplace} [id BJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   | | |Subtensor{int64} [id BK] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   | | | |GpuShape [id W] <TensorType(int64, vector)> ''
 |   |     | |   |   | | | |   |   | | | |Constant{3} [id BL] <int64>
 |   |     | |   |   | | | |   |   | | |Elemwise{sub,no_inplace} [id BM] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   | |   |Shape_i{3} [id BN] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   | |   | |conv1_W [id BH] <CudaNdarrayType(float32, 5D)>
 |   |     | |   |   | | | |   |   | |   |TensorConstant{1} [id BI] <TensorType(int8, scalar)>
 |   |     | |   |   | | | |   |   | |Elemwise{add,no_inplace} [id BO] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |   |Subtensor{int64} [id BP] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |   | |GpuShape [id W] <TensorType(int64, vector)> ''
 |   |     | |   |   | | | |   |   |   | |Constant{4} [id BQ] <int64>
 |   |     | |   |   | | | |   |   |   |Elemwise{sub,no_inplace} [id BR] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |     |Shape_i{4} [id BS] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |     | |conv1_W [id BH] <CudaNdarrayType(float32, 5D)>
 |   |     | |   |   | | | |   |   |     |TensorConstant{1} [id BI] <TensorType(int8, scalar)>
 |   |     | |   |   | | | |   |   |GpuFromHost [id X] <CudaNdarrayType(float32, 5D)> ''
 |   |     | |   |   | | | |   |   |ScalarFromTensor [id BT] <int64> ''
 |   |     | |   |   | | | |   |   | |Elemwise{int_div,no_inplace} [id BU] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |   |Elemwise{sub,no_inplace} [id BF] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |   |TensorConstant{2} [id BV] <TensorType(int8, scalar)>
 |   |     | |   |   | | | |   |   |ScalarFromTensor [id BW] <int64> ''
 |   |     | |   |   | | | |   |   | |Elemwise{add,no_inplace} [id BX] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |   |Subtensor{int64} [id BD] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |   |Elemwise{int_div,no_inplace} [id BU] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |ScalarFromTensor [id BY] <int64> ''
 |   |     | |   |   | | | |   |   | |Elemwise{int_div,no_inplace} [id BZ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |   |Elemwise{sub,no_inplace} [id BM] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |   |TensorConstant{2} [id BV] <TensorType(int8, scalar)>
 |   |     | |   |   | | | |   |   |ScalarFromTensor [id CA] <int64> ''
 |   |     | |   |   | | | |   |   | |Elemwise{add,no_inplace} [id CB] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |   |Subtensor{int64} [id BK] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |   |Elemwise{int_div,no_inplace} [id BZ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |ScalarFromTensor [id CC] <int64> ''
 |   |     | |   |   | | | |   |   | |Elemwise{int_div,no_inplace} [id CD] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |   |Elemwise{sub,no_inplace} [id BR] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |   |   |TensorConstant{2} [id BV] <TensorType(int8, scalar)>
 |   |     | |   |   | | | |   |   |ScalarFromTensor [id CE] <int64> ''
 |   |     | |   |   | | | |   |     |Elemwise{add,no_inplace} [id CF] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |       |Subtensor{int64} [id BP] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |       |Elemwise{int_div,no_inplace} [id CD] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |MakeVector{dtype='int64'} [id CG] <TensorType(int64, vector)> ''
 |   |     | |   |   | | | |     |Elemwise{mul,no_inplace} [id CH] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |     | |Shape_i{0} [id CI] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |     | | |convolution3d_input_1 [id Y] <TensorType(float32, 5D)>
 |   |     | |   |   | | | |     | |Elemwise{add,no_inplace} [id BC] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |     |Shape_i{1} [id CJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |     | |convolution3d_input_1 [id Y] <TensorType(float32, 5D)>
 |   |     | |   |   | | | |     |Elemwise{add,no_inplace} [id BJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |     |Elemwise{add,no_inplace} [id BO] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |GpuContiguous [id CK] <CudaNdarrayType(float32, 4D)> ''
 |   |     | |   |   | | | | |GpuReshape{4} [id CL] <CudaNdarrayType(float32, 4D)> ''
 |   |     | |   |   | | | |   |GpuDimShuffle{0,2,1,3,4} [id CM] <CudaNdarrayType(float32, 5D)> ''
 |   |     | |   |   | | | |   | |conv1_W [id BH] <CudaNdarrayType(float32, 5D)>
 |   |     | |   |   | | | |   |MakeVector{dtype='int64'} [id CN] <TensorType(int64, vector)> ''
 |   |     | |   |   | | | |     |Elemwise{mul,no_inplace} [id CO] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |     | |Shape_i{0} [id CP] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |     | | |conv1_W [id BH] <CudaNdarrayType(float32, 5D)>
 |   |     | |   |   | | | |     | |Shape_i{2} [id BG] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |     |Shape_i{1} [id CQ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |     | |conv1_W [id BH] <CudaNdarrayType(float32, 5D)>
 |   |     | |   |   | | | |     |Shape_i{3} [id BN] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |     |Shape_i{4} [id BS] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |GpuAllocEmpty [id CR] <CudaNdarrayType(float32, 4D)> ''
 |   |     | |   |   | | | | |Elemwise{switch,no_inplace} [id CS] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |Elemwise{eq,no_inplace} [id CT] <TensorType(int8, scalar)> ''
 |   |     | |   |   | | | | | | |Elemwise{mul,no_inplace} [id CH] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |TensorConstant{-1} [id CU] <TensorType(int8, scalar)>
 |   |     | |   |   | | | | | |Elemwise{int_div,no_inplace} [id CV] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |Elemwise{mul,no_inplace} [id CW] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | |Shape_i{0} [id CI] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | |Elemwise{add,no_inplace} [id BC] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | |Shape_i{1} [id CJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | |Elemwise{add,no_inplace} [id BJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | |Elemwise{add,no_inplace} [id BO] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |Elemwise{neg,no_inplace} [id CX] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |   |Elemwise{mul,no_inplace} [id CY] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |     |Elemwise{mul,no_inplace} [id CH] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |     |Shape_i{1} [id CJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |     |Elemwise{add,no_inplace} [id BJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |     |Elemwise{add,no_inplace} [id BO] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |Elemwise{mul,no_inplace} [id CH] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | |Elemwise{switch,no_inplace} [id CZ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |Elemwise{eq,no_inplace} [id DA] <TensorType(int8, scalar)> ''
 |   |     | |   |   | | | | | | |Elemwise{mul,no_inplace} [id CO] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |TensorConstant{-1} [id CU] <TensorType(int8, scalar)>
 |   |     | |   |   | | | | | |Elemwise{int_div,no_inplace} [id DB] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |Elemwise{mul,no_inplace} [id DC] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | |Shape_i{0} [id CP] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | |Shape_i{2} [id BG] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | |Shape_i{1} [id CQ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | |Shape_i{3} [id BN] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | |Shape_i{4} [id BS] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |Elemwise{neg,no_inplace} [id DD] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |   |Elemwise{mul,no_inplace} [id DE] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |     |Elemwise{mul,no_inplace} [id CO] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |     |Shape_i{1} [id CQ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |     |Shape_i{3} [id BN] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |     |Shape_i{4} [id BS] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |Elemwise{mul,no_inplace} [id CO] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | |Elemwise{add,no_inplace} [id DF] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |Elemwise{int_div,no_inplace} [id DG] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |Elemwise{sub,no_inplace} [id DH] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | |Elemwise{add,no_inplace} [id DI] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | | |Elemwise{switch,no_inplace} [id DJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | | | |Elemwise{eq,no_inplace} [id DK] <TensorType(int8, scalar)> ''
 |   |     | |   |   | | | | | | | | | | |Elemwise{add,no_inplace} [id BJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | | | | |TensorConstant{-1} [id CU] <TensorType(int8, scalar)>
 |   |     | |   |   | | | | | | | | | |Elemwise{int_div,no_inplace} [id CV] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | | | |Elemwise{add,no_inplace} [id BJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | | |TensorConstant{0} [id DL] <TensorType(int8, scalar)>
 |   |     | |   |   | | | | | | | |Elemwise{switch,no_inplace} [id DM] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |   |Elemwise{eq,no_inplace} [id DN] <TensorType(int8, scalar)> ''
 |   |     | |   |   | | | | | | |   | |Shape_i{3} [id BN] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |   | |TensorConstant{-1} [id CU] <TensorType(int8, scalar)>
 |   |     | |   |   | | | | | | |   |Elemwise{int_div,no_inplace} [id DB] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |   |Shape_i{3} [id BN] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |TensorConstant{1} [id BI] <TensorType(int8, scalar)>
 |   |     | |   |   | | | | | |TensorConstant{1} [id BI] <TensorType(int8, scalar)>
 |   |     | |   |   | | | | |Elemwise{add,no_inplace} [id DO] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |Elemwise{int_div,no_inplace} [id DP] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | |Elemwise{sub,no_inplace} [id DQ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | | |Elemwise{add,no_inplace} [id DR] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | | | |Elemwise{switch,no_inplace} [id DS] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | | | | |Elemwise{eq,no_inplace} [id DT] <TensorType(int8, scalar)> ''
 |   |     | |   |   | | | |   | | | | | |Elemwise{add,no_inplace} [id BO] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | | | | | |TensorConstant{-1} [id CU] <TensorType(int8, scalar)>
 |   |     | |   |   | | | |   | | | | |Elemwise{int_div,no_inplace} [id CV] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | | | | |Elemwise{add,no_inplace} [id BO] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | | | |TensorConstant{0} [id DL] <TensorType(int8, scalar)>
 |   |     | |   |   | | | |   | | |Elemwise{switch,no_inplace} [id DU] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | |   |Elemwise{eq,no_inplace} [id DV] <TensorType(int8, scalar)> ''
 |   |     | |   |   | | | |   | |   | |Shape_i{4} [id BS] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | |   | |TensorConstant{-1} [id CU] <TensorType(int8, scalar)>
 |   |     | |   |   | | | |   | |   |Elemwise{int_div,no_inplace} [id DB] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | |   |Shape_i{4} [id BS] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | |TensorConstant{1} [id BI] <TensorType(int8, scalar)>
 |   |     | |   |   | | | |   |TensorConstant{1} [id BI] <TensorType(int8, scalar)>
 |   |     | |   |   | | | |GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='conv', precision='float32'} [id DW] <CDataType{cudnnConvolutionDescriptor_t}> ''
 |   |     | |   |   | | | | |MakeVector{dtype='int64'} [id DX] <TensorType(int64, vector)> ''
 |   |     | |   |   | | | | | |Elemwise{switch,no_inplace} [id CS] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |Elemwise{switch,no_inplace} [id DY] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |Elemwise{eq,no_inplace} [id DZ] <TensorType(int8, scalar)> ''
 |   |     | |   |   | | | | | | | |Shape_i{1} [id CJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | | |TensorConstant{-1} [id CU] <TensorType(int8, scalar)>
 |   |     | |   |   | | | | | | |Elemwise{int_div,no_inplace} [id CV] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | | |Shape_i{1} [id CJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |Elemwise{switch,no_inplace} [id DJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | | |Elemwise{switch,no_inplace} [id DS] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | | |MakeVector{dtype='int64'} [id EA] <TensorType(int64, vector)> ''
 |   |     | |   |   | | | |   |Elemwise{switch,no_inplace} [id CZ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |Elemwise{switch,no_inplace} [id EB] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | |Elemwise{eq,no_inplace} [id EC] <TensorType(int8, scalar)> ''
 |   |     | |   |   | | | |   | | |Shape_i{1} [id CQ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | | |TensorConstant{-1} [id CU] <TensorType(int8, scalar)>
 |   |     | |   |   | | | |   | |Elemwise{int_div,no_inplace} [id DB] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   | |Shape_i{1} [id CQ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |Elemwise{switch,no_inplace} [id DM] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |   |Elemwise{switch,no_inplace} [id DU] <TensorType(int64, scalar)> ''
 |   |     | |   |   | | | |Constant{1.0} [id ED] <float32>
 |   |     | |   |   | | | |Constant{0.0} [id EE] <float32>
 |   |     | |   |   | | |MakeVector{dtype='int64'} [id EF] <TensorType(int64, vector)> ''
 |   |     | |   |   | |   |Shape_i{0} [id CI] <TensorType(int64, scalar)> ''
 |   |     | |   |   | |   |Elemwise{add,no_inplace} [id BC] <TensorType(int64, scalar)> ''
 |   |     | |   |   | |   |Shape_i{0} [id CP] <TensorType(int64, scalar)> ''
 |   |     | |   |   | |   |Shape_i{2} [id BG] <TensorType(int64, scalar)> ''
 |   |     | |   |   | |   |Elemwise{add,no_inplace} [id EG] <TensorType(int64, scalar)> ''
 |   |     | |   |   | |   | |Elemwise{sub,no_inplace} [id EH] <TensorType(int64, scalar)> ''
 |   |     | |   |   | |   | | |Elemwise{add,no_inplace} [id BJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | |   | | |Shape_i{3} [id BN] <TensorType(int64, scalar)> ''
 |   |     | |   |   | |   | |TensorConstant{1} [id BI] <TensorType(int8, scalar)>
 |   |     | |   |   | |   |Elemwise{add,no_inplace} [id EI] <TensorType(int64, scalar)> ''
 |   |     | |   |   | |     |Elemwise{sub,no_inplace} [id EJ] <TensorType(int64, scalar)> ''
 |   |     | |   |   | |     | |Elemwise{add,no_inplace} [id BO] <TensorType(int64, scalar)> ''
 |   |     | |   |   | |     | |Shape_i{4} [id BS] <TensorType(int64, scalar)> ''
 |   |     | |   |   | |     |TensorConstant{1} [id BI] <TensorType(int8, scalar)>
 |   |     | |   |   | |TensorConstant{1} [id BI] <TensorType(int8, scalar)>
 |   |     | |   |   | |TensorConstant{3} [id EK] <TensorType(int8, scalar)>
 |   |     | |   |   |MakeVector{dtype='int64'} [id EL] <TensorType(int64, vector)> ''
 |   |     | |   |     |Elemwise{mul,no_inplace} [id EM] <TensorType(int64, scalar)> ''
 |   |     | |   |     | |Elemwise{mul,no_inplace} [id EN] <TensorType(int64, scalar)> ''
 |   |     | |   |     | | |Shape_i{0} [id EO] <TensorType(int64, scalar)> ''
 |   |     | |   |     | | | |DiagonalSubtensor [id M] <CudaNdarrayType(float32, 6D)> ''
 |   |     | |   |     | | |Shape_i{1} [id EP] <TensorType(int64, scalar)> ''
 |   |     | |   |     | |   |DiagonalSubtensor [id M] <CudaNdarrayType(float32, 6D)> ''
 |   |     | |   |     | |Shape_i{2} [id EQ] <TensorType(int64, scalar)> ''
 |   |     | |   |     |   |DiagonalSubtensor [id M] <CudaNdarrayType(float32, 6D)> ''
 |   |     | |   |     |Shape_i{3} [id ER] <TensorType(int64, scalar)> ''
 |   |     | |   |     | |DiagonalSubtensor [id M] <CudaNdarrayType(float32, 6D)> ''
 |   |     | |   |     |Elemwise{mul,no_inplace} [id ES] <TensorType(int64, scalar)> ''
 |   |     | |   |       |Shape_i{4} [id ET] <TensorType(int64, scalar)> ''
 |   |     | |   |       | |DiagonalSubtensor [id M] <CudaNdarrayType(float32, 6D)> ''
 |   |     | |   |       |Shape_i{5} [id EU] <TensorType(int64, scalar)> ''
 |   |     | |   |         |DiagonalSubtensor [id M] <CudaNdarrayType(float32, 6D)> ''
 |   |     | |   |MakeVector{dtype='int64'} [id EV] <TensorType(int64, vector)> ''
 |   |     | |     |Shape_i{0} [id EO] <TensorType(int64, scalar)> ''
 |   |     | |     |Shape_i{1} [id EP] <TensorType(int64, scalar)> ''
 |   |     | |     |Shape_i{2} [id EQ] <TensorType(int64, scalar)> ''
 |   |     | |     |Shape_i{4} [id ET] <TensorType(int64, scalar)> ''
 |   |     | |     |Shape_i{5} [id EU] <TensorType(int64, scalar)> ''
 |   |     | |GpuReshape{5} [id EW] <CudaNdarrayType(float32, (True, False, True, True, True))> ''
 |   |     |   |conv1_b [id EX] <CudaNdarrayType(float32, vector)>
 |   |     |   |TensorConstant{[ 1 64  1  1  1]} [id EY] <TensorType(int64, vector)>
 |   |     |GpuElemwise{Abs,no_inplace} [id EZ] <CudaNdarrayType(float32, 5D)> ''
 |   |       |GpuElemwise{add,no_inplace} [id H] <CudaNdarrayType(float32, 5D)> ''
 |   |Join [id FA] <TensorType(int64, vector)> ''
 |     |TensorConstant{0} [id DL] <TensorType(int8, scalar)>
 |     |DimShuffle{x} [id FB] <TensorType(int64, (True,))> ''
 |     | |Prod{acc_dtype=int64} [id FC] <TensorType(int64, scalar)> ''
 |     |   |MakeVector{dtype='int64'} [id FD] <TensorType(int64, vector)> ''
 |     |     |Shape_i{0} [id EO] <TensorType(int64, scalar)> ''
 |     |     |Shape_i{2} [id EQ] <TensorType(int64, scalar)> ''
 |     |     |Shape_i{5} [id EU] <TensorType(int64, scalar)> ''
 |     |TensorConstant{(1,) of 1} [id FE] <TensorType(int64, (True,))>
 |     |MakeVector{dtype='int64'} [id FF] <TensorType(int64, vector)> ''
 |       |Shape_i{4} [id ET] <TensorType(int64, scalar)> ''
 |       |Shape_i{1} [id EP] <TensorType(int64, scalar)> ''
 |TensorConstant{[2 1]} [id FG] <TensorType(int64, vector)>
 |TensorConstant{[2 1]} [id FG] <TensorType(int64, vector)>
 |TensorConstant{(2,) of 0} [id FH] <TensorType(int64, vector)>

Storage map footprint:
 - GpuReshape{6}.0, Shape: (16, 18, 64, 3, 112, 112), ElemSize: 4 Byte(s), TotalSize: 2774532096 Byte(s)
 - DiagonalSubtensor.0, Shape: (16, 16, 64, 3, 112, 112), ElemSize: 4 Byte(s), TotalSize: 2466250752 Byte(s)
 - GpuContiguous.0, Shape: (114688, 1, 112, 16), ElemSize: 4 Byte(s), TotalSize: 822083584 Byte(s)
 - GpuElemwise{add,no_inplace}.0, Shape: (16, 64, 16, 112, 112), ElemSize: 4 Byte(s), TotalSize: 822083584 Byte(s)
 - GpuElemwise{Abs,no_inplace}.0, Shape: (16, 64, 16, 112, 112), ElemSize: 4 Byte(s), TotalSize: 822083584 Byte(s)
 - GpuAlloc{memset_0=True}.0, Shape: (16, 64, 18, 58, 58), ElemSize: 4 Byte(s), TotalSize: 248020992 Byte(s)
 - fc6_W, Shared Input, Shape: (8192, 4096), ElemSize: 4 Byte(s), TotalSize: 134217728 Byte(s)
 - <CudaNdarrayType(float32, matrix)>, Shared Input, Shape: (8192, 4096), ElemSize: 4 Byte(s), TotalSize: 134217728 Byte(s)
 - <CudaNdarrayType(float32, matrix)>, Shared Input, Shape: (4096, 4096), ElemSize: 4 Byte(s), TotalSize: 67108864 Byte(s)
 - fc7_W, Shared Input, Shape: (4096, 4096), ElemSize: 4 Byte(s), TotalSize: 67108864 Byte(s)
 - GpuContiguous.0, Shape: (288, 3, 114, 114), ElemSize: 4 Byte(s), TotalSize: 44914176 Byte(s)
 - convolution3d_input_1, Input, Shape: (16, 3, 16, 112, 112), ElemSize: 4 Byte(s), TotalSize: 38535168 Byte(s)
 - conv4b_W, Shared Input, Shape: (512, 512, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 28311552 Byte(s)
 - conv5a_W, Shared Input, Shape: (512, 512, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 28311552 Byte(s)
 - conv5b_W, Shared Input, Shape: (512, 512, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 28311552 Byte(s)
 - <CudaNdarrayType(float32, 5D)>, Shared Input, Shape: (512, 512, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 28311552 Byte(s)
 - <CudaNdarrayType(float32, 5D)>, Shared Input, Shape: (512, 512, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 28311552 Byte(s)
 - <CudaNdarrayType(float32, 5D)>, Shared Input, Shape: (512, 512, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 28311552 Byte(s)
 - conv4a_W, Shared Input, Shape: (512, 256, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 14155776 Byte(s)
 - <CudaNdarrayType(float32, 5D)>, Shared Input, Shape: (512, 256, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 14155776 Byte(s)
 - fc7x_W, Shared Input, Shape: (487, 4096), ElemSize: 4 Byte(s), TotalSize: 7979008 Byte(s)
 - <CudaNdarrayType(float32, matrix)>, Shared Input, Shape: (4096, 487), ElemSize: 4 Byte(s), TotalSize: 7979008 Byte(s)
 - <CudaNdarrayType(float32, matrix)>, Shared Input, Shape: (487, 4096), ElemSize: 4 Byte(s), TotalSize: 7979008 Byte(s)
 - fc8_W, Shared Input, Shape: (4096, 487), ElemSize: 4 Byte(s), TotalSize: 7979008 Byte(s)
 - <CudaNdarrayType(float32, 5D)>, Shared Input, Shape: (256, 256, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 7077888 Byte(s)
 - conv3b_W, Shared Input, Shape: (256, 256, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 7077888 Byte(s)
 - conv3a_W, Shared Input, Shape: (256, 128, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 3538944 Byte(s)
 - <CudaNdarrayType(float32, 5D)>, Shared Input, Shape: (256, 128, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 3538944 Byte(s)
 - fc8x_W, Shared Input, Shape: (4096, 201), ElemSize: 4 Byte(s), TotalSize: 3293184 Byte(s)
 - <CudaNdarrayType(float32, matrix)>, Shared Input, Shape: (4096, 201), ElemSize: 4 Byte(s), TotalSize: 3293184 Byte(s)
 - conv2_W, Shared Input, Shape: (128, 64, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 884736 Byte(s)
 - <CudaNdarrayType(float32, 5D)>, Shared Input, Shape: (128, 64, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 884736 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (92160,), ElemSize: 4 Byte(s), TotalSize: 368640 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (92160,), ElemSize: 4 Byte(s), TotalSize: 368640 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (92160,), ElemSize: 4 Byte(s), TotalSize: 368640 Byte(s)
 - <CudaNdarrayType(float32, 5D)>, Shared Input, Shape: (64, 3, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 20736 Byte(s)
 - conv1_W, Shared Input, Shape: (64, 3, 3, 3, 3), ElemSize: 4 Byte(s), TotalSize: 20736 Byte(s)
 - fc7_b, Shared Input, Shape: (4096,), ElemSize: 4 Byte(s), TotalSize: 16384 Byte(s)
 - fc7x_b, Shared Input, Shape: (4096,), ElemSize: 4 Byte(s), TotalSize: 16384 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (4096,), ElemSize: 4 Byte(s), TotalSize: 16384 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (4096,), ElemSize: 4 Byte(s), TotalSize: 16384 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (4096,), ElemSize: 4 Byte(s), TotalSize: 16384 Byte(s)
 - fc6_b, Shared Input, Shape: (4096,), ElemSize: 4 Byte(s), TotalSize: 16384 Byte(s)
 - fc8x_target, Input, Shape: (16, 201), ElemSize: 4 Byte(s), TotalSize: 12864 Byte(s)
 - GpuFromHost.0, Shape: (16, 201), ElemSize: 4 Byte(s), TotalSize: 12864 Byte(s)
 - conv5a_b, Shared Input, Shape: (512,), ElemSize: 4 Byte(s), TotalSize: 2048 Byte(s)
 - conv5b_b, Shared Input, Shape: (512,), ElemSize: 4 Byte(s), TotalSize: 2048 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (512,), ElemSize: 4 Byte(s), TotalSize: 2048 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (512,), ElemSize: 4 Byte(s), TotalSize: 2048 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (512,), ElemSize: 4 Byte(s), TotalSize: 2048 Byte(s)
 - conv4a_b, Shared Input, Shape: (512,), ElemSize: 4 Byte(s), TotalSize: 2048 Byte(s)
 - conv4b_b, Shared Input, Shape: (512,), ElemSize: 4 Byte(s), TotalSize: 2048 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (512,), ElemSize: 4 Byte(s), TotalSize: 2048 Byte(s)
 - fc8_b, Shared Input, Shape: (487,), ElemSize: 4 Byte(s), TotalSize: 1948 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (487,), ElemSize: 4 Byte(s), TotalSize: 1948 Byte(s)
 - conv3a_b, Shared Input, Shape: (256,), ElemSize: 4 Byte(s), TotalSize: 1024 Byte(s)
 - conv3b_b, Shared Input, Shape: (256,), ElemSize: 4 Byte(s), TotalSize: 1024 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (256,), ElemSize: 4 Byte(s), TotalSize: 1024 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (256,), ElemSize: 4 Byte(s), TotalSize: 1024 Byte(s)
 - fc8x_b, Shared Input, Shape: (201,), ElemSize: 4 Byte(s), TotalSize: 804 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (201,), ElemSize: 4 Byte(s), TotalSize: 804 Byte(s)
 - conv2_b, Shared Input, Shape: (128,), ElemSize: 4 Byte(s), TotalSize: 512 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (128,), ElemSize: 4 Byte(s), TotalSize: 512 Byte(s)
 - conv1_b, Shared Input, Shape: (64,), ElemSize: 4 Byte(s), TotalSize: 256 Byte(s)
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (64,), ElemSize: 4 Byte(s), TotalSize: 256 Byte(s)
 - fc8x_sample_weights, Input, Shape: (16,), ElemSize: 4 Byte(s), TotalSize: 64 Byte(s)
 - TensorConstant{[  1 512  ..1   1   1]}, Shape: (5,), ElemSize: 8 Byte(s), TotalSize: 40 Byte(s)
 - Join.0, Shape: (5,), ElemSize: 8 Byte(s), TotalSize: 40 Byte(s)
 - TensorConstant{[ 1 64  1  1  1]}, Shape: (5,), ElemSize: 8 Byte(s), TotalSize: 40 Byte(s)
 - TensorConstant{[  1 256  ..1   1   1]}, Shape: (5,), ElemSize: 8 Byte(s), TotalSize: 40 Byte(s)
 - Join.0, Shape: (5,), ElemSize: 8 Byte(s), TotalSize: 40 Byte(s)
 - TensorConstant{[  1 128  ..1   1   1]}, Shape: (5,), ElemSize: 8 Byte(s), TotalSize: 40 Byte(s)
 - Join.0, Shape: (4,), ElemSize: 8 Byte(s), TotalSize: 32 Byte(s)
 - MakeVector{dtype='int64'}.0, Shape: (4,), ElemSize: 8 Byte(s), TotalSize: 32 Byte(s)
 - TensorConstant{[2 1]}, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - TensorConstant{(2,) of 0}, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - TensorConstant{(2,) of 2}, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - TensorConstant{[1 2]}, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - Constant{1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{add,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{add,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{2}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{1}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{int_div,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{int_div,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1,) of 1}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{3}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{3}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{2}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{1}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{add,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{add,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{0}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{4}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{add,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{5}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{2}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{4}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{0}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{2}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{mul,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{sub,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{int_div,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{3}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{4}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{int_div,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{4}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{sub,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{sub,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{switch,no_inplace}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - CudaNdarrayConstant{1.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - CudaNdarrayConstant{[[[[[ 0.5]]]]]}, Shape: (1, 1, 1, 1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{0.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - CudaNdarrayConstant{[[  1.00000001e-07]]}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - <CudaNdarrayType(float32, scalar)>, Shared Input, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - <CudaNdarrayType(float32, scalar)>, Shared Input, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - <CudaNdarrayType(float32, scalar)>, Shared Input, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - GpuFromHost.0, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{[[ 0.5]]}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1, 1) of 0.5}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1, 1) of 1e-07}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{[[[[[[ 0.]]]]]]}, Shape: (1, 1, 1, 1, 1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{[[ 1.]]}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - Constant{1.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - Constant{0.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - <CudaNdarrayType(float32, scalar)>, Shared Input, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - CudaNdarrayConstant{[[ 0.99999988]]}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{[[ 0.]]}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1, 1) of 1.0}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - keras_learning_phase, Input, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - TensorConstant{1}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - TensorConstant{-1}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - TensorConstant{3}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - TensorConstant{0}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - TensorConstant{2}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - TensorConstant{(1,) of 0}, Shape: (1,), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 TotalSize: 8702143395.0 Byte(s) 8.105 GB
 TotalSize inputs: 702161255.0 Byte(s) 0.654 GB

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
srun: error: c8: task 0: Exited with exit code 1

```
In summary the GpuDnnPool operation fails with no more details.

On my network the input data are clips of videos, so the tensor has 5 dimensions: batchs samples, colour channels, temporal lenght, height and width. I have done some variations and trying to reduce the batch of the data from 32 to 8 going through 16. This error stop appearing at batch size 8. 

Taking a look deeper on the implementation of the operation is failing, I found that the pool 2D operation does a reshape when the input tensor is higher than 4D. This reshape consist on the [following](https://github.com/Theano/Theano/blob/master/theano/tensor/signal/pool.py#L94):
```
    # extract image dimensions
    img_shape = input.shape[-2:]

    # count the number of "leading" dimensions, store as dmatrix
    batch_size = tensor.prod(input.shape[:-2])
    batch_size = tensor.shape_padright(batch_size, 1)

    # store as 4D tensor with shape: (batch_size,1,height,width)
    new_shape = tensor.cast(tensor.join(0, batch_size,
                                        tensor.as_tensor([1]),
                                        img_shape), 'int64')
    input_4D = tensor.reshape(input, new_shape, ndim=4)

    # downsample mini-batch of images
    op = Pool(ds, ignore_border, st=st, padding=padding,
              mode=mode)
    output = op(input_4D)

    # restore to original shape
    outshp = tensor.join(0, input.shape[:-2], output.shape[-2:])
    return tensor.reshape(output, outshp, ndim=input.ndim)
```
This reshape causes to end up in my network into a tensor with the following shape: `(114688, 1, 112, 16)`. I haven't never contributed to Theano and nearly catch the C code implementations, but seems to me that my GPU is trying to allocate a tensor with a dimension (in this case the first one) so high that is not abel to do it and raises a RuntimeException.

I would like to know if the previous implementation of the 2D pool for tensors higher than 5D could be done in a more effective way, and also in addition if a 3D pool operation could be done so the optimisation will be higher.

Thank you so much for your help!

**Comment by nouiz** [comment]
One of the dimensions is very big. It could be that it take too much time
to compute and bust the 5s limit per kernel. What is your OS? Do you share
your GPU with the monitor? What is the GPU?

cudnn support 3d pooling. So instead of doing 2 2d pooling to compute 3d
pooling, you could call the cudnn pooling directly. Maybe this is faster?

**Comment by bryanyzhu** [comment]
@albertomontesg  Did you solve this problem? I am training C3D now, and encounter the same problem. Thanks a lot.

**Comment by albertomontesg** [comment]
@bryanyzhu yes I changed at keras the operation and I set to do the 3D convolution and 3D pooling with the theano module `theano.sandbox.cuda.nnet`. This implementations work great.

**Comment by bryanyzhu** [comment]
@albertomontesg Thanks, are you referring to theano.sandbox.cuda.fftconv.conv3d_fft this operation? or theano.sandbox.cuda.dnn.GpuDnnConv3d? 

I directly search theano.sandbox.cuda.nnet on google, but no useful documentation shows up. Could you advise through(like give me an example about 3d conv, 3d pool), or update the model.py [here](https://github.com/albertomontesg/keras-model-zoo/blob/master/models/C3D-Sports1M/model.py) to handle the large batch size issue? Thank you very much.

**Comment by nouiz** [comment]
What about reshaping this from:
(114688, 1, 112, 16)
to
(114688/N, N, 112, 16)

This can make an difference in the implementation and could make this work.
Be sure to test it with cudnn v5, as they could have fixed this.

If you try this and it still don't work, tell me.

**Comment by brunodoamaral** [comment]
I too have the same as @bryanyzhu. Mine is related to Kera's MaxPooling3D (If I drop it from my network it works).

**Comment by bryanyzhu** [comment]
@brunodoamaral me too. Any luck using theano.sandbox.cuda.nnet? I couldn't find any useful api information about it.

**Comment by brunodoamaral** [comment]
@bryanyzhu I couldn't find it too. The only think that gets my model running is reduce the batch size. Maybe there is a memory issue being masked by this generic exception.

**Comment by nouiz** [comment]
did one of you tried what I suggested 2 days ago?

**Comment by bryanyzhu** [comment]
@nouiz  Thanks for following this issue. I haven't tried them yet, will upgrade to cudnn v5 first to see. And will do the reshaping later.

**Comment by albertomontesg** [comment]
@nouiz I did tried and gpu the error disappear, but because Keras was implementing 3D pooling with two 2D pooling, I decided to use the `theano.sandbox.cuda.dnn.dnn_pool` which worked perfectly fine for me.

**Comment by zzero** [comment]
@albertomontesg Could you provide the snippet of the code showing how you combined the keras 3d pooling with theano.sandbox.cuda.dnn.dnn_pool? I tried to do this myself, but ran into errors.

**Comment by albertomontesg** [comment]
@zzero https://github.com/albertomontesg/keras/blob/feature/improve-3d-pool/keras/backend/theano_backend.py#L964 Here is the code I modified and worked for me

**Comment by zzero** [comment]
@albertomontesg Thanks! works like magic :+1:

**Comment by nouiz** [comment]
I'm not sure the status of this PR. I think it is that the fondamental problem isn't fixed, but this can be worked around? Can someone confirm?

**Comment by zzero** [comment]
@nouiz Yes, that is the status. The fundamental problem is in Theano inefficiently trying to perform 3d pooling. The workaround is using the  cuda's dnn_pool instead of the one provided by Theano, which @albertomontesg has provided in his code.

**Comment by nouiz** [comment]
What do you mean Theano not being efficient in 3d pooling? I don't know any theano 3d pooling except cudnn. So I guess you mean using a Theano graph with 2d pooling to mimic 3d pooling.

So I have done a new issue on implementing a 3d pooling on CPU: https://github.com/Theano/Theano/issues/4731

I'm closing this issue, but if I missed something, tell it.

**Comment by LuoDQ** [comment]
when I change the theano backend to use dnn.dnn_pool for pool2d,
I get error like:
`Layer conv2d_2 was called with an input that isn't a symbolic tensor. Received type:<class 'theano.sandbox.cuda.var.CudaNdarrayVariable'>. Full input:[GpuDnnPool{mode='max'}.0]. All inputs to the layer should be tensors.`

How do you solve this?

**Comment by nouiz** [comment]
Call
theano.tensor.signal.pool.pool2d

Instead.

**Comment by LuoDQ** [comment]
@nouiz 
if I use pool.pool_2d as it originally is, when the batch size exceed 64, it reports error as:

    GpuDnnPool: error doing cudnnPoolingForward operation: CUDNN_STATUS_EXECUTION_FAILED

**Comment by nouiz** [comment]
Try to update cudnn version. Otherwise, what are the version of cuda, cudnn
and Theano do you use?
