### ISSUE TITLE
could not create cuDNN handle with cuDNN 5.0rc

### ISSUE THREAD

**Issue by aristid** [Theano/Theano#4411]
I'm using the latest Theano 0.9.0.dev0 on Windows 7. After updating the cuDNN to 5.0rc the following error is displayed (cuDNN 4 runs fine):

```
H:\ai>python mnist_cnn.py
Using Theano backend.
DEBUG: nvcc STDOUT mod.cu
   Creating library C:/Users/IK/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.11-64/tmp
hj_xmu/265abc51f7c376c224983485238ff1a5.lib and object C:/Users/IK/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_St
epping_3_GenuineIntel-2.7.11-64/tmphj_xmu/265abc51f7c376c224983485238ff1a5.exp

Using gpu device 0: GeForce GTX 960 (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 5004)
X_train shape: (60000L, 1L, 28L, 28L)
60000 train samples
10000 test samples
DEBUG: nvcc STDOUT mod.cu
   Creating library C:/Users/IK/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.11-64/tmp
xvxy5v/0cfdd4ad6c74bf444cd6fffa3e66a079.lib and object C:/Users/IK/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_St
epping_3_GenuineIntel-2.7.11-64/tmpxvxy5v/0cfdd4ad6c74bf444cd6fffa3e66a079.exp

Traceback (most recent call last):
  File "mnist_cnn.py", line 71, in <module>
    verbose=1, validation_data=(X_test, Y_test))
  File "C:\Anaconda2\lib\site-packages\keras\models.py", line 402, in fit
    sample_weight=sample_weight)
  File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 986, in fit
    self._make_test_function()
  File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 666, in _make_test_function
    **self._function_kwargs)
  File "C:\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 509, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "C:\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 495, in __init__
    **kwargs)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function.py", line 322, in function
    output_keys=output_keys)
  File "C:\Anaconda2\lib\site-packages\theano\compile\pfunc.py", line 480, in pfunc
    output_keys=output_keys)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1818, in orig_function
    defaults)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1682, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Anaconda2\lib\site-packages\theano\gof\link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Anaconda2\lib\site-packages\theano\gof\vm.py", line 1021, in make_all
    no_recycling))
  File "C:\Anaconda2\lib\site-packages\theano\sandbox\cuda\__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "C:\Anaconda2\lib\site-packages\theano\gof\op.py", line 978, in make_thunk
    no_recycling)
  File "C:\Anaconda2\lib\site-packages\theano\gof\op.py", line 881, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "C:\Anaconda2\lib\site-packages\theano\sandbox\cuda\nvcc_compiler.py", line 414, in compile_str
    return dlimport(lib_filename)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 299, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
RuntimeError: ('The following error happened while compiling the node', GpuDnnPool{mode='max'}(GpuContiguous.0, TensorConstant{(2L,) of 2}, TensorCons
tant{(2L,) of 2}, TensorConstant{(2L,) of 0}), '\n', 'could not create cuDNN handle: CUDNN_STATUS_INTERNAL_ERROR', "[GpuDnnPool{mode='max'}(<CudaNdarr
ayType(float32, 4D)>, TensorConstant{(2L,) of 2}, TensorConstant{(2L,) of 2}, TensorConstant{(2L,) of 0})]")
```

I'm running the example from Keras (https://raw.githubusercontent.com/fchollet/keras/master/examples/mnist_cnn.py). It happens without Keras, too. Here's my theanorc.txt:
```
[global]
floatX = float32
device = gpu0
mode = FAST_RUN

[nvcc]
fastmath = True
flags=-LC:\Anaconda2\libs
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin

[lib]
cnmem = 1
```

**Comment by nouiz** [comment]
Try with "cnmem = 0.9". Sometimes it fixes this type of error. How much
memory your GPU have? Can you tell me the highest value cnmem work?

**Comment by aristid** [comment]
Thank you, it works with "cnmem = 0.9". The highest value where it still works is 0.94. I have GTX 960 with 4MB RAM. With CuDNN, it worked with "cnmem=1" though, so something has changed.

**Comment by nouiz** [comment]
Do you share that GPU with your monitor?

We cap 1 to 0.95, so if something else changed, then this could explain
that.

Maybe cudnn need more memory now.

**Comment by aristid** [comment]
No, the monitors use on-board GPUs, the GTX 960 is for Cuda only.
