### ISSUE TITLE
cudnn issues since upgrading to 5, but only with optimizer on...

### ISSUE THREAD

**Issue by braingineer** [Theano/Theano#4490]
hi all,

reported here as well: https://github.com/fchollet/keras/issues/2678

Error is below. I have tried it with and without CNMeM.  I have tried it with downgrading theano and upgrading (though, i'm currently at the state @nouiz reocmmended for #4485).    If if run the following with `THEANO_FLAGS='optimizer=None' python ....`, it runs fine.  (and the code i'm running is just keras example code found [here](https://github.com/fchollet/keras/blob/master/examples/imdb_cnn.py))

Thanks

```
(DL)cogniton [examples] $ python imdb_cnn.py 
Using Theano backend.
Using gpu device 0: GeForce GTX 980 (CNMeM is enabled with initial size: 10.0% of memory, cuDNN 5004)
Loading data...
20000 train sequences
5000 test sequences
Pad sequences (samples x time)
X_train shape: (20000, 400)
X_test shape: (5000, 400)
Build model...
Traceback (most recent call last):
  File "imdb_cnn.py", line 84, in <module>
    validation_data=(X_test, y_test))
  File "/home/cogniton/research/code/keras/keras/models.py", line 405, in fit
    sample_weight=sample_weight)
  File "/home/cogniton/research/code/keras/keras/engine/training.py", line 996, in fit
    self._make_test_function()
  File "/home/cogniton/research/code/keras/keras/engine/training.py", line 676, in _make_test_function
    **self._function_kwargs)
  File "/home/cogniton/research/code/keras/keras/backend/theano_backend.py", line 517, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/cogniton/research/code/keras/keras/backend/theano_backend.py", line 503, in __init__
    **kwargs)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/compile/function.py", line 322, in function
    output_keys=output_keys)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/compile/pfunc.py", line 480, in pfunc
    output_keys=output_keys)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/compile/function_module.py", line 1824, in orig_function
    defaults)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/compile/function_module.py", line 1688, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/gof/vm.py", line 1021, in make_all
    no_recycling))
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/gof/op.py", line 969, in make_thunk
    no_recycling)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/gof/op.py", line 872, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/gof/cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/gof/cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py", line 415, in compile_str
    return dlimport(lib_filename)
  File "/home/cogniton/anaconda/envs/DL/lib/python2.7/site-packages/theano/gof/cmodule.py", line 299, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
RuntimeError: ('The following error happened while compiling the node', GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty.0, GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0}), '\n', 'could not create cuDNN handle: CUDNN_STATUS_NOT_INITIALIZED', "[GpuDnnConv{algo='small', inplace=True}(<CudaNdarrayType(float32, (False, False, False, True))>, <CudaNdarrayType(float32, 4D)>, <CudaNdarrayType(float32, 4D)>, <CDataType{cudnnConvolutionDescriptor_t}>, Constant{1.0}, Constant{0.0})]")
```

**Comment by braingineer** [comment]
Fixed the issue.  I found some hints that an earlier mucking up of the cuda drivers might have prevented me from upgrading fully, so I did a full OS reinstall, grabbed cuda 7.5 and cudnn5 and now everything works.

cheers
b.
