### ISSUE TITLE
Is it possible to import theano by two different programs at the same time?

### ISSUE THREAD

**Issue by sunshineatnoon** [Theano/Theano#4508]
I have a website which uses theano, when starting the server, I have to start two python scripts which all import theano, so I got this error:

```
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device gpu failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1
```

If I use CPU backend, then it works fine. During the execution, only one python script will actually use theano. So I'm thinking if it is possible to import theano twice at the same time, or may the second one can fall back on CPU so I can get rid of this error?

**Comment by abergeron** [comment]
This is exactly what happens, one of them falls back to the CPU and prints this message.  It doesn't crash or anything.

**Comment by nouiz** [comment]
If you want both to use the GPU, use a smaller value for cnmem. Currently
you tell Theano to grab too much memory for the first process, so the
second don't have enough. You can try cnmem=0.4

**Comment by sunshineatnoon** [comment]
@nouiz @abergeron Thanks for your help, by changing cnmem=0.4, I can start Django server and Celery worker, but when running Celery worker, I got this error:

`MemoryError: ('Error allocating 1728 bytes of device memory (CNMEM_STATUS_CUDA_ERROR).', "you might consider using 'theano.shared(..., borrow=True)'")`

1728 bytes seems a really small piece memory, how could theano fail to allocate that much of memory?

**Comment by sunshineatnoon** [comment]
I found the [solution](http://stackoverflow.com/questions/33354272/runtimeerror-when-using-theano-shared-variable-in-a-celery-celery-worker) on StackOverFlow, problem solved.
