### ISSUE TITLE
Can't use GPU,Cuda error: kernel_reduce_ccontig_node_97496c4d3cf9a06dc4082cc141f 918d2_0: invalid device function

### ISSUE THREAD

**Issue by orbitzhan** [Theano/Theano#4938]
**Steps:**
1. install CUDA and Theano and add path to system path
2. cmd >>>python 
3. import theano

**Error:**
C:\Users\zhhan>python
Python 2.7.12 |Anaconda 4.1.1 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.
1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import theano
Using gpu device 0: GeForce 610M (CNMeM is disabled, cuDNN not available)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\theano\__init__.py", line 111, in <module
>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "C:\Anaconda2\lib\site-packages\theano\sandbox\cuda\tests\test_driver.py"
, line 38, in test_nvidia_driver1
    if not numpy.allclose(f(), a.sum()):
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line
871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\Anaconda2\lib\site-packages\theano\gof\link.py", line 314, in raise_w
ith_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line
859, in __call__
    outputs = self.fn()
RuntimeError: Cuda error: kernel_reduce_ccontig_node_97496c4d3cf9a06dc4082cc141f
918d2_0: invalid device function . (grid: 1 x 1; block: 256 x 1 x 1)

Apply node that caused the error: GpuCAReduce{add}{1}(<CudaNdarrayType(float32,
vector)>)
Toposort index: 0
Inputs types: [CudaNdarrayType(float32, vector)]
Inputs shapes: [(10000,)]
Inputs strides: [(1,)]
Inputs values: ['not shown']
Outputs clients: [[HostFromGpu(GpuCAReduce{add}{1}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-tr
ace of when this node was created. This can be done with by setting the Theano f
lag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be
 disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storag
e map footprint of this apply node.

**My Computer information**
Win7 
8G
Corei5-2520
GeForce 610M 

**.theanorc.txt**
[global]
openmp=False
device = gpu
floatX = float32
allow_input_downcast=True
[blas]
ldflags=
[gcc]
cxxflags=-IC:\Anaconda2\MinGW 
[nvcc]
flags = -LC:\Anaconda2\libs 
compiler_bindir = D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin 
fastmath = True
flags=-arch=sm_30

**Comment by orbitzhan** [comment]
I try to remove the code in .theanorc.txt, and it works. But I don't know if it effect the use of Theano.
>`flags=-arch=sm_30`

**Comment by lamblin** [comment]
GT 610M have a compute capability of 2.1, so generating code for 3.0 by passing `-arch=sm_30` cannot work.
It is better in general not to specivy `-arch=sm_...` if you can avoid it, as Theano will detect automatically the capability of your card.
