### ISSUE TITLE
 cuda_runtime.h: No such file or directory (or CUDA is installed, but device gpu is not available )

### ISSUE THREAD

**Issue by rayset** [Theano/Theano#4945]
I have cuda 8.0 and cudnn installed, and they work with torch. I read a lot of possible solution here and on stack overflow, but nothing worked.

here is my .theanorc:
```

[global]
floatX=float32
device=gpu

[nvcc]
flags=-D_FORCE_INLINES 


[cuda]
root=/usr/local/cuda
```
this is the error I get (after 5000 lines of code)

```
`===============================
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:60:1: fatal error: cuda_runtime.h: No such file or directory
 #endif
 ^
compilation terminated.

['nvcc', '-shared', '-O3', '-m64', '-Xcompiler', '-D_FORCE_INLINES,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/rayset/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/cuda_ndarray', '-I/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda', '-I/usr/lib/python2.7/dist-packages/numpy/core/include', '-I/usr/include/python2.7', '-I/usr/local/lib/python2.7/dist-packages/theano/gof', '-o', '/home/rayset/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/cuda_ndarray/cuda_ndarray.so', 'mod.cu', '-L/usr/lib', '-lcublas', '-lpython2.7', '-lcudart']
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -m64 -Xcompiler -D_FORCE_INLINES,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/rayset/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/cuda_ndarray -I/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/theano/gof -o /home/rayset/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/cuda_ndarray/cuda_ndarray.so mod.cu -L/usr/lib -lcublas -lpython2.7 -lcudart')
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)
```
`

CUDA works on torch for sure and so does cudnn, g++ and c++ return 4.9.3 to --version. UBUNTU 16.

in $THEANO_FLAGS I tried everything (empty atm) and  $CUDA_ROOT is empty too.

**Comment by nouiz** [comment]
Do you have multiple nvcc version installed? If so, this could be the
cause. The Theano flags  cuda.root isn't always working. So you are better
to not use it if it don't work. Make sure that nvcc is in your PATH and
LIBRARY_PATH and LD_LIBRARY_PATH as it is supposed to be. If it still don't
work, give the values of those env variable.

**Comment by rayset** [comment]
I just finished formatting, installing ubuntu 14.04 and now it works perfectly. I guess it's something with g++ and gcc version that has issues with cuda and what not (maybe I did something really strange to the paths), the path variables were fine. I had problems with cudnn path too, so it may be linked.

Thanks anyway, if someone from the future reads here: Ubuntu 14 works.
