### ISSUE TITLE
Ubuntu 16.10 and CUDA

### ISSUE THREAD

**Issue by carlthome** [Theano/Theano#5117]
I've updated from Ubuntu 16.04 to 16.10. Before the update Theano worked with GPU support. After running the dist-upgrade successfully however, Theano cannot compile anymore. I've tested clearing the cache with `theano-cache purge` and simply removing ~/.theano entirely. Neither fixed anything.

```sh
python -c "import theano"

['nvcc', '-shared', '-O3', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/carl/.theano/compiledir_Linux-4.8--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/cuda_ndarray', '-I/home/carl/anaconda3/lib/python3.5/site-packages/theano/sandbox/cuda', '-I/home/carl/anaconda3/lib/python3.5/site-packages/numpy/core/include', '-I/home/carl/anaconda3/include/python3.5m', '-I/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof', '-L/home/carl/anaconda3/lib', '-o', '/home/carl/.theano/compiledir_Linux-4.8--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/cuda_ndarray/cuda_ndarray.so', 'mod.cu', '-lcublas', '-lpython3.5m', '-lcudart']

ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -m64 -Xcompiler -DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/carl/.theano/compiledir_Linux-4.8--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/cuda_ndarray -I/home/carl/anaconda3/lib/python3.5/site-packages/theano/sandbox/cuda -I/home/carl/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/carl/anaconda3/include/python3.5m -I/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof -L/home/carl/anaconda3/lib -o /home/carl/.theano/compiledir_Linux-4.8--generic-x86_64-with-debian-stretch-sid-x86_64-3.5.2-64/cuda_ndarray/cuda_ndarray.so mod.cu -lcublas -lpython3.5m -lcudart')
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)
```

# CUDA version
```sh
nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44
```

# Theano version
```sh
pip show theano

---
Metadata-Version: 1.1
Name: Theano
Version: 0.9.0.dev3
Summary: Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.
Home-page: http://deeplearning.net/software/theano/
Author: LISA laboratory, University of Montreal
Author-email: theano-dev@googlegroups.com
License: BSD
Location: /home/carl/anaconda3/lib/python3.5/site-packages
Requires: numpy, scipy, six
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Education
  Intended Audience :: Science/Research
  Intended Audience :: Developers
  License :: OSI Approved :: BSD License
  Programming Language :: Python
  Topic :: Software Development :: Code Generators
  Topic :: Software Development :: Compilers
  Topic :: Scientific/Engineering :: Mathematics
  Operating System :: Microsoft :: Windows
  Operating System :: POSIX
  Operating System :: Unix
  Operating System :: MacOS
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
```

# .theanorc
```sh
[global]
device=gpu
floatX=float32

[nvcc]
flags=-D_FORCE_INLINES
```

**Comment by carlthome** [comment]
It seems like the dist-upgrade reset the default gcc version to a too new version for CUDA (sigh...). Running `sudo update-alternatives --config gcc` and choosing a version older than gcc-5 is one solution for getting Theano to compile again. Problem solved.

**Comment by nouiz** [comment]
We had this problem recently. We did fix in Theano for that. To our
knowledge or now work with the master of Theano and the default gcc from
Ubuntu 16.10 and cuda 8.

**Comment by carlthome** [comment]
Great news!
