### ISSUE TITLE
pygpu.gpuarray.GpuArrayException: b'unspecified launch failure'

### ISSUE THREAD

**Issue by laudney** [Theano/Theano#5611]
Hi there

I'm trying to train some CNN. Randomly, 30-40 epochs into the training, the following error would occur. I'm afraid I don't have a simple way to reproduce it but by looking at the error message (the bit _Outputs clients: [[InplaceGpuDimShuffle{1,0,2,3}(GpuFromHost<None>.0)]]_) I think it's related to the issue #5589 I raised a few days ago.

I'm running Theano git HEAD on Linux + NVIDIA Titan X.

> Traceback (most recent call last):
  File "/home/user/.conda/envs/default/lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 664, in pygpu.gpuarray.pygpu_fromhostdata (pygpu/gpuarray.c:9647)
  File "pygpu/gpuarray.pyx", line 301, in pygpu.gpuarray.array_copy_from_host (pygpu/gpuarray.c:5613)
pygpu.gpuarray.GpuArrayException: b'unspecified launch failure'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/user/.conda/envs/default/lib/python3.5/site-packages/keras/engine/training.py", line 1196, in fit
    initial_epoch=initial_epoch)
  File "/home/user/.conda/envs/default/lib/python3.5/site-packages/keras/engine/training.py", line 891, in _fit_loop
    outs = f(ins_batch)
  File "/home/user/.conda/envs/default/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 959, in __call__
    return self.function(*inputs)
  File "/home/user/.conda/envs/default/lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/user/.conda/envs/default/lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/user/.conda/envs/default/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.conda/envs/default/lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 664, in pygpu.gpuarray.pygpu_fromhostdata (pygpu/gpuarray.c:9647)
  File "pygpu/gpuarray.pyx", line 301, in pygpu.gpuarray.array_copy_from_host (pygpu/gpuarray.c:5613)
pygpu.gpuarray.GpuArrayException: b'unspecified launch failure'
Apply node that caused the error: GpuFromHost<None>(convolution2d_19_target)
Toposort index: 98
Inputs types: [TensorType(float32, 4D)]
Inputs shapes: [(10, 1, 512, 512)]
Inputs strides: [(1048576, 1048576, 2048, 4)]
Inputs values: ['not shown']
Outputs clients: [[InplaceGpuDimShuffle{1,0,2,3}(GpuFromHost<None>.0)]]
HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by nouiz** [comment]
It is not the same issue.

Can you run your jobs with then env variable CUDA_LAUNCH_BLOCKING=1?

As the execution on the GPU is asynchrone, it provide bad error. With that,
it will run slower, but give better error message.

**Comment by laudney** [comment]
OK

**Comment by laudney** [comment]
With CUDA_LAUNCH_BLOCKING=1, training has been running for 100 epochs so far without any error.

This is getting tricky to reproduce.

**Comment by lamblin** [comment]
Are you sharing that Titan X with a display?
If so, it may be possible that the X server, needing more memory at some point, silently grabbed (and corrupted) memory in use by CUDA.

**Comment by laudney** [comment]
The PC is headless and it has 3 Titan X in it. It does have Xorg server running in the background but I don't think it's the cause because:

1. I've encountered the same error on all 3 cards.
2. The error didn't exist when i was running the Theano git HEAD I pulled in mid-Jan. It only appeared when I pulled again a few days ago.

With CUDA_LAUNCH_BLOCKING=1, I have two training sessions running on two cards, now over 200 epochs without any error whatsoever.

**Comment by laudney** [comment]
After multiple training sessions overnight, I confirm that with CUDA_LAUNCH_BLOCKING=1, the error is gone.

**Comment by nouiz** [comment]
That isn't great. It make debugging much more complicated. You should not need to run with that as it slow down computation.

Can you remove that flag and try with this one: gpuarray.sync=True?

They are similar, but not 100% compatible.

@abergeron do you have other ideas?

**Comment by abergeron** [comment]
Maybe disabling the allocation cache and running under cuda-memcheck could find something.  However it's going to be super slow.

Here is how to do it.

`THEANO_FLAGS=gpuarray.preallocate=-1,<other flags> cuda-memcheck python <your script>`

**Comment by laudney** [comment]
With: gpuarray.sync=True (and nothing else), I cannot even load my saved Keras model. Theano compilation error below:

>   File "/.../lib/python3.5/site-packages/keras/models.py", line 178, in load_model
    model._make_train_function()
  File "/.../lib/python3.5/site-packages/keras/engine/training.py", line 767, in _make_train_function
    **self._function_kwargs)
  File "/.../lib/python3.5/site-packages/keras/backend/theano_backend.py", line 969, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/.../lib/python3.5/site-packages/keras/backend/theano_backend.py", line 955, in __init__
    **kwargs)
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/compile/function_module.py", line 1795, in orig_function
    defaults)
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/compile/function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gof/vm.py", line 1063, in make_all
    impl=impl))
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gof/cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gof/cmodule.py", line 1118, in module_from_key
    src_code = lnk.get_src_code()
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gof/cc.py", line 1462, in get_src_code
    mod = self.get_dynamic_module()
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gof/cc.py", line 1506, in get_dynamic_module
    self.code_gen()
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gof/cc.py", line 826, in code_gen
    behavior = op.c_code(node, name, isyms, osyms, sub)
  File "/.../lib/python3.5/site-packages/Theano-0.9.0rc1-py3.5.egg/theano/gpuarray/nnet.py", line 223, in c_code
    """ % locals()
KeyError: ('The following error happened while compiling the node', GpuCrossentropySoftmaxArgmax1HotWithBias(InplaceGpuDimShuffle{1,0}.0, GpuElemwise{second,no_inplace}.0, GpuElemwise{Cast{int64}}[]<gpuarray>.0), '\n', 'z')

**Comment by laudney** [comment]
I've started training with gpuarray.preallocate=-1 and cuda-memcheck and will let you know if the error occurs again. But it's running at extremely slow speed.

**Comment by laudney** [comment]
48 hours of non-stop training later no error has occurred with gpuarray.preallocate=-1 and cuda-memcheck.

I'm afraid i'm unable to reproduce it with any of the extra flag you have suggested.

**Comment by abergeron** [comment]
Can you try again with only `gpuarray.preallocate=-1`.  It should be much faster.

If that works, it means either there is a problem with the allocation cache or there is a synchronization problem somewhere.

**Comment by laudney** [comment]
With only gpuarray.preallocate=-1, I've done 2 trainings of 100 epochs each. No error whatsoever.

**Comment by abergeron** [comment]
It seems this is a problem with synchronization somewhere, which makes it really hard to debug without access to the code.  Do you have some code that you can send us to reproduce this?

As a temporary workaround you can keep using preallocate=-1, but it's going to be a bit slower.

**Comment by laudney** [comment]
Yeah, this type of bugs are the hardest to reproduce, understand and fix. Unfortunately my code as it stands is very complicated. It will take a while for me to get to a small test case to reproduce it.

It may not even be bug in Theano. It could be the nvidia kernel module I upgraded to. I use Archlinux which has rolling release.

**Comment by gyuanfan** [comment]
I have a similar issue. it is not reproducible.  Was there any recent changes in theano that caused this?


    reraise(exc_type, exc_value, exc_trace)

  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__

    self.fn() if output_subset is None else\

RuntimeError: Cuda error: k_elemwise_unary_rowmajor_copy: unspecified launch failure. (n_blocks=3829, n_threads_per_block=256)



Apply node that caused the error: GpuAlloc(GpuElemwise{Composite{(i0 * (Composite{(((i0 - i1) * i2) + i3)}(i1, i2, i3, i4) + Abs(Composite{(((i0 - i1) * i2) + i3)}(i1, i2, i3, i4))))}}[(0, 1)].0, TensorConstant{1}, TensorConstant{16}, TensorConstant{175}, TensorConstant{175}, TensorConstant{2})

Toposort index: 225

Inputs types: [CudaNdarrayType(float32, (False, False, False, False, True)), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int8, scalar)]

Inputs shapes: [(1, 16, 175, 175, 1), (), (), (), (), ()]

Inputs strides: [(0, 30625, 175, 1, 0), (), (), (), (), ()]

Inputs values: ['not shown', array(1), array(16), array(175), array(175), array(2, dtype=int8)]

Outputs clients: [[Rebroadcast{0}(GpuAlloc.0)]]



HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by lamblin** [comment]
I don't think there has been a recent change in the old back-end, which you are using.
The old back-end is not supported any more and will be deleted from the development version soon.
Do you have any issue with that code on the new back-end?

**Comment by gyuanfan** [comment]
can you please keep the old back-end for a couple of months?  i am not
sure what you mean by new backend, and if I need to retrain every
thing with the new back end. thanks a ton.

**Comment by nouiz** [comment]
Can you always use the old back-end by using the Theano release 0.9. It is
not because it go away from the dev version that you can't use it anymore!

If you save just the weithgs and not the theano graph or theano function,
then you should not need to retrain.

Fred

**Comment by nouiz** [comment]
Since the original problems, there was much update to the new back-end. Do you still have problems with the new back-end?

**Comment by gyuanfan** [comment]
so far so good.

thanks a ton.

**Comment by laudney** [comment]
I'm happy to report that all is good. Thank you so much for the efforts!!

**Comment by nouiz** [comment]
thanks for the confirmation.
