### ISSUE TITLE
Intermittent CuDNN status not supported

### ISSUE THREAD

**Issue by astooke** [Theano/Theano#5654]
Hi,

  Using a convnet with a couple layers under `theano.gpuarray.dnn.dnn_conv()`, CUDA-8.0, and CuDNN 5105, and I've gotten this error intermittently while computing a gradient:

```
RuntimeError: error doing operation: CUDNN_STATUS_NOT_SUPPORTED
Apply node that caused the error: GpuDnnConvGradW{algo='none', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty{dtype='float32', context_name=None}.0, GpuDnnConvDesc{border_mode=(0, 0), subsample=(2, 2), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0})
Toposort index: 119
Inputs types: [GpuArrayType<None>(float32, (False, True, False, False)), GpuArrayType<None>(float32, (False, False, False, False)), GpuArrayType<None>(float32, (False, True, False, False)), <theano.gof.type.CDataType object at 0x7fcdb15e3e80>, Scalar(float32), Scalar(float32)]
Inputs shapes: [(16518, 1, 84, 84), (16518, 16, 41, 41), (16, 1, 4, 4), 'No shapes', (), ()]
Inputs strides: [(28224, 28224, 336, 4), (107584, 6724, 164, 4), (64, 64, 16, 4), 'No strides', (), ()]
Inputs values: ['not shown', 'not shown', 'not shown', <capsule object NULL at 0x7fcda6715ea0>, 1.0, 0.0]
Outputs clients: [[GpuReshape{1}(GpuDnnConvGradW{algo='none', inplace=True}.0, TensorConstant{(1,) of -1})]]
```

Most of the time, the code runs fine.  I've seen this a couple of times over maybe a hundred calls, in different runs.  I don't know where to begin to isolate this.   Doesn't look like it has anything to do with the recent `float64` issue?

p.s. Did bleeding-edge Theano and PyGPU upgrades today.

Thanks,
Adam

**Comment by gurunathpr** [comment]
Will upgrading the version to one with GpuDnnConvGradW with the precision variable work?

**Comment by astooke** [comment]
I have just updated again to bleeding edge, so I assume that has the precision variable work in it?  If not, I'm happy to try with instructions.

I just noticed a pattern.  When I call the function on large data inputs, it fails with an `out of memory` error, as expected.  When I call the function with a small amount of data, it runs OK.  When I run it with some intermediate amounts, it fails with this `CUDNN_STATUS_NOT_SUPPORTED` error.  This is now happening consistently.  Maybe it is actually an out of memory error?  The function is complicated--it's a hessian-vector product.

**Comment by lamblin** [comment]
I don't think the blacklisted driver would be the issue here, as long as you are using the latest Theano, and bypassing the check.
Could it be that you have `floatX=float64` on the P100?

An intermittent issue may be due to the sharing of a compute GPU with a display, since the display can sometimes use more memory than others, and might also silently "steal" and corrupt memory used by CUDA.
However, if it is now happening consistently, I don't think it would be it. Can you confirm that it is always `GpuDnnConvGradW{algo='none'}` that fails?

**Comment by astooke** [comment]
OK I went back and did a more detailed test, and it turns out that the problem hits both computers at the same data size.  The `16518` above was the batch size, and I both computers get the `CUDNN_STATUS` error right about there.  Turns out to correspond to about 6 GB peak memory, looking in `nvidia-smi`.

When I run a similar problem but without a convnet, I get the expected result that the P100 can hold twice as much data.  Both machines give only an OOM error, and only as the memory usage shown in `nvidia-smi` during the computation creeps up past the GPU size.

Btw is there a way to capture max memory usage under the new backend?  I only saw instructions under the old backend.  Maybe more easily monitored external to Theano but I haven't looked into it.

**Comment by lamblin** [comment]
OK, it makes more sense to me now.
I think you have hit a limitation of cuDNN, either in the total size of a tensor, or the number of elements across one dimension.
With an even larger batch size, you would get a MemoryError at a different point during the execution.

I don't think there is anything we can do in Theano itself for that issue, but here are options you could try:
- use cuDNN v6 or a pre-version, if / when you can get access to it
- use a different algo for GpuDnnConvGradW, for instance by setting dnn.conv.algo_bwd_filter to another value
- disable cuDNN convolutions (which should fall back to the CorrMM implementation). This may use more memory altogether, though.

To capture max memory usage with the new back-end, I usually just let the default memory pre-allocator do its job, initializing it with a small amount (or 0), and check the GPU memory usage with nvidia-smi.

**Comment by astooke** [comment]
Thanks for the advice!  I tested the `dnn.conv.algo_bwd_filter` options, here is a summary of results in case it helps anyone:

`deterministic` and `small` do not suffer this issue--they work all the way up until OOM.  `none` and `fft` both suffer the `CUDNN_STATUS` error at the same batch size.  The biggest batch size (admittedly arbitrary units) before OOM was about 18k on the GTX 1080 and 38k on the P100 for `deterministic`, and very nearly the same amount for `small`.  Both `none` and `fft` maxed out at about 16k, again leaving significant memory headroom in the P100.  In the end, though, `none` and `fft` were a little faster in this case.  It's faster to use these filters, call the function twice and accumulate the result than it is to call the function once with the other filters.   

Thanks for the help I am up and running!

**Comment by astooke** [comment]
p.s. No option to use winograd currently?  Otherwise I would have tried it.

**Comment by lamblin** [comment]
`guess_*` and `time_*` could select winograd automatically if applicable, but Theano does not expose it yet directly. This is something we plan on working on.
Also, cuDNN v6 rc0 seems to be available according to #5679.
