### ISSUE TITLE
error while using conv2d_grad_wrt_weights in GPU

### ISSUE THREAD

**Issue by yiyak** [Theano/Theano#5788]
Hi,

I am calculating the gradients using conv2d_grad_wrt_weights in con2d layer with the following code, it works only in CPU but not GPU, however.

it seems caused by the same problem in #3347, but I still can not solve the problem after reading it.

Here is the code:

```
import numpy
import theano

theano.config.compute_test_value = 'off'
theano.config.optimizer='fast_run'
theano.config.floatX = 'float32'
theano.config.warn_float64='warn'
theano.config.on_unused_input='warn'


def test_compile1():
    a = theano.tensor.tensor4(name = 'a')
    d = theano.tensor.tensor4(name = 'd')
    output = theano.tensor.nnet.abstract_conv.conv2d_grad_wrt_weights(a, d, [40, 20, 5, 5], border_mode='valid')
    f = theano.function([a, d], output)
    return f

func = test_compile1()


t3 = numpy.array(range(20*13*13*100), dtype = 'float32').reshape((100, 20, 13, 13))
t4 = numpy.array(range(40*9*9*100), dtype = 'float32').reshape((100, 40, 9, 9))


print func(t3, t4)[0][0]

```

and the error:

```
Traceback (most recent call last):
  File "wrt_test.py", line 26, in <module>
    print func(t3, t4)[0][0]
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
RuntimeError: GpuDnnConvGradW: error doing operation: CUDNN_STATUS_BAD_PARAM
Apply node that caused the error: GpuDnnConvGradW{algo='none', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty.0, GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0})
Toposort index: 13
Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), <theano.gof.type.CDataType object at 0x7f5c681f8a50>, Scalar(float32), Scalar(float32)]
Inputs shapes: [(100, 20, 13, 13), (100, 40, 9, 9), (40, 20, 40, 20), 'No shapes', (), ()]
Inputs strides: [(3380, 169, 13, 1), (3240, 81, 9, 1), (16000, 800, 20, 1), 'No strides', (), ()]
Inputs values: ['not shown', 'not shown', 'not shown', <PyCObject object at 0x7f5c687d1800>, 1.0, 0.0]
Inputs name: ('image', 'grad', 'output', 'descriptor', 'alpha', 'beta')

Outputs clients: [[HostFromGpu(GpuDnnConvGradW{algo='none', inplace=True}.0)]]
```

Thank you very much

**Comment by lamblin** [comment]
I just tried with the latest master, new back-end (device=cuda), cuDNN version 5105, and it worked correctly (result below). I checked that the graph had been optimized to use GpuDnnConvGradW as well.
Which version of Theano, cuda, cudnn, libgpuarray are you using?

```
[[  2.91461682e+14   2.91460373e+14   2.91459031e+14   2.91457823e+14
    2.91456481e+14]
 [  2.91444804e+14   2.91443529e+14   2.91442187e+14   2.91440945e+14
    2.91439636e+14]
 [  2.91427926e+14   2.91426651e+14   2.91425275e+14   2.91424000e+14
    2.91422725e+14]
 [  2.91411082e+14   2.91409639e+14   2.91408431e+14   2.91407156e+14
    2.91405814e+14]
 [  2.91394137e+14   2.91392828e+14   2.91391486e+14   2.91390244e+14
    2.91388902e+14]]
```

**Comment by yiyak** [comment]
Theano 0.8.2, Cuda driver 370.28, cuda version 8.0.44, libgpuarray version

It now works with the new back end, I was using the older one (device = gpu)

Thank you very much!

**Comment by lamblin** [comment]
No problem. Please use Theano 0.9 if you can, now that it has been released.
