### ISSUE TITLE
Convolution with new backend

### ISSUE THREAD

**Issue by radluki** [Theano/Theano#5871]
When i run convolution I get different results on GPU and CPU, which is normal to certain extent. If i run with old backen (device=gpu) errors are small. But when I run with device=cuda, the results are incorrect.
To compare those errors I wrote some scripts. For gpu errors are 1e-7, and for cuda 0.7.
If I don't use indexing with lscalar i convolution works properly, but i want to process data in batches.
There are no error messages.

Here are some scripts:
test.py : 
```
import pickle
import numpy as np
import theano as t
import theano.tensor as T
from theano.tensor.nnet import conv2d
import sys
from theano.tensor.signal.pool import pool_2d
"""
Script loads data generated by generate_dat.py,
computes convolution and saves result to a file
"""
with open('data.pickle','rb') as f:
    d = pickle.load(f)

print('image shape = '+str(d['image'].shape))
image = t.shared(d['image'], borrow=True)
filters = t.shared(d['filters'], borrow=True)
ishape = d['ishape']
fshape = d['fshape']

#image = image.reshape(ishape)
im1 = T.matrix('im1')
ishape2 = (2, *ishape[1:])
print('ishape2 = ',ishape2)
im2 = im1.reshape(ishape2)
conv_out = conv2d(input=im2, filters=filters, filter_shape=fshape, input_shape=ishape)

i = T.lscalar('i')
eval_conv =  t.function([i],[conv_out],givens={ im1 : image[i:i+2] })

c_out = np.array(eval_conv(2))

with open(sys.argv[1],'wb') as f:
    pickle.dump(c_out,f)
#print(c_out)
```

Data is generated by generate_data.py : 
```
import numpy as np
import pickle
import theano

ishape = (20,1,28,28)
ishape_2 = (20,28*28)
image = np.asarray(np.random.normal(size=ishape_2),dtype=theano.config.floatX)
fshape = (100,1,5,5)
filters = np.asarray(np.random.normal(size=fshape), dtype=theano.config.floatX)

print('[INFO] Writing data to file.')
with open('data.pickle','wb') as f:
    d = {'ishape':ishape,'image':image,'fshape':fshape,'filters':filters}
    pickle.dump(d,f)
print('[INFO] Execution finished.')
```

Results are compared by compare.py : 
```
import pickle
import sys
import numpy as np

with open(sys.argv[1],'rb') as f:
    d1 = pickle.load(f)

with open(sys.argv[2],'rb') as f:
    d2 = pickle.load(f)
a1 = np.sum(np.abs(d1))
a2 = np.sum(np.abs(d2))
a3 = a1+a2
print(np.sum(np.abs(d1-d2))/a3)
```

Test can be run using following commands:
```
python generate_data.py
THEANO_FLAGS=device=cpu python test.py cpu_data.pickle
THEANO_FLAGS=device=gpu python test.py gpu_data.pickle
python compare.py cpu_data.pickle gpu_data.pickle
THEANO_FLAGS=device=cuda python test.py gpu_data.pickle
python compare.py cpu_data.pickle gpu_data.pickle
```
When using cuda convolution returns totally incorrect results, too big to be caused by rounding.

**Comment by nouiz** [comment]
Which Theano version do you use? Can you try with the dev version?

**Comment by radluki** [comment]
I use 0.9.0 version.

**Comment by lamblin** [comment]
Which version of Cuda, and if relevant, cuDNN are you using?
Does it still happen if you disable cudnn?

**Comment by radluki** [comment]
I use Cuda 8, nvcc --version gives:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

When it comes to cuDNN initially I used v6, but because of warnings I installed v5.1, which is compatibile with theano. When I run scripts with device=gpu I get:
```
[INFO] Writing data to file.
[INFO] Execution finished.
CPU test
image shape = (20, 784)
ishape2 =  (2, 1, 28, 28)
GPU test
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GT 820M (CNMeM is enabled with initial size: 95.0% of memory, cuDNN not available)
image shape = (20, 784)
ishape2 =  (2, 1, 28, 28)
3.28761e-08
```
When with cuda:
```
[INFO] Writing data to file.
[INFO] Execution finished.
CPU test
image shape = (20, 784)
ishape2 =  (2, 1, 28, 28)
GPU test
Can not use cuDNN on context None: Device not supported
Mapped name None to device cuda: GeForce GT 820M (0000:01:00.0)
image shape = (20, 784)
ishape2 =  (2, 1, 28, 28)
0.707148
```
I don't know why it can not use cuDNN. Maybe compute capability level of my gpu is less than 3, but I thought it was equal 3, at nvidia site I can only find GeForce 820M which is 2.1, is it the same GPU as GeForce GT 820M?  Also I use Arch Linux.

My .theanorc:
```
[global]
floatX = float32
device = cpu
cxx = /usr/bin/g++-5
# optimizer_excluding=cudnn

[lib]
icnmem = 1

[gpuarray]
#preallocate = 1

[cuda]
root = /opt/cuda

[dnn]
library_path =/home/lukira/builds/external/cudnn-8.0-linux-x64-v5.1/cuda/lib64
include_path =/home/lukira/builds/external/cudnn-8.0-linux-x64-v5.1/cuda/include
#enable = 'False'

[nvcc]
fastmath = True
```
When I uncomment dnn.enable='False', or  optimizer_excluding=cudnn nothing changes.
Also when I run:
```
THEANO_FLAGS=''; python -c "import theano; theano.test()"
```
It runs for 4 hours and finnally finishes with segmentation fault. There is no information about errors other than that. I tried theano instalation from pip, from aur, but nothing helps.

This simple code that I presented shows that something is wrong with convolutions. When I try to learn convolutional network it in fact does not learn at all if I use new backend.
What is interesting, when I use Keras implementation convolutional networks learn. But it may be that keras changes my flag device=cuda to device=gpu, but I don't know for sure.

**Comment by ReyhaneAskari** [comment]
I tested this. There are several things that I changed:
1. I avoided loading the data from a pickle and generated the data using a seed for the randomizer.
2. I added flag : ```floatX = float32```, as this causes different precision. Without specifying the type, part of the code might run on CPU even when you set the device to GPU or CUDA.
3. I changed the code such that we no longer use the input as given. Given brings the data to the memory. 

So the results show : 
1. The output of cuda and gpu are both the same.
2. The output of cuda and gpu both differ from cpu with 4.74128e-08.
3. Since ```numpy.allclose``` has a tolerance of 1e-8, comparing the output of cpu vs gpu (cuda) returns false.
4. Checking the maximum difference of output matrixes ( ```np.max(np.abs(d1 - d2))```), results in a difference of 4.7683716e-06 which is relatively large. 

@lamblin, @nouiz  what do you suggest?

Test.py
```python
import numpy as np
import theano
import pickle
import theano.tensor as T
from theano.tensor.nnet import conv2d
import sys
np.random.seed(0)


image_shape = (2, 1, 28, 28)
image = np.asarray(np.random.normal(size=image_shape),
                   dtype=theano.config.floatX)
filter_shape = (100, 1, 5, 5)
filters = np.asarray(np.random.normal(size=filter_shape),
                     dtype=theano.config.floatX)

filters = theano.shared(filters, borrow=True)

img = T.tensor4('img')
conv_out = conv2d(
    input=img,
    filters=filters,
    filter_shape=filter_shape,
    input_shape=image_shape)

f = theano.function([img], conv_out)

c_out = np.array(f(image))
print np.sum(np.abs(c_out))
with open(sys.argv[1], 'wb') as f:
    pickle.dump(c_out, f)

```
compare.py

```python
import pickle
import sys
import numpy as np

with open(sys.argv[1], 'rb') as f:
    d1 = pickle.load(f)

with open(sys.argv[2], 'rb') as f:
    d2 = pickle.load(f)
a1 = np.sum(np.abs(d1))
a2 = np.sum(np.abs(d2))
a3 = a1 + a2
print(np.sum(np.abs(d1 - d2)) / a3)
print(np.allclose(d1, d2))

```

**Comment by lamblin** [comment]
Numerical relative and absolute errors can be higher in float32 than the default of `numpy.allclose`, but still be within regular numerical precision range.
For instance, in Theano, we use relative and absolute tolerance of `1e-5` for `float32` tensors.

So I see nothing wrong in @ReyhaneAskari's results. To be sure, could you try calling `numpy.allclose(..., atol=1e-5, rtol=1e-5)` and confirm it works?
What had me worried is the 0.7 relative difference mentioned originally, but that can be explained away if the absolute difference is small for that element.

**Comment by ReyhaneAskari** [comment]
Thanks, @lamblin. The results of ```np.allclose(d1, d2, atol=1e-5, rtol=1e-5)``` when comparing _cpu vs gpu_ and _cpu vs cuda_ are both true.

**Comment by radluki** [comment]
Thank you for your reply, but I know that it all works without indexing. I have written that in my first message. I have run your code and it works as well on my machine. What I was asking about is this two lines:
```
i = T.lscalar('i')
eval_conv =  t.function([i],[conv_out],givens={ im1 : image[i:i+2] })
```
Why does it work with device=gpu, but not with device=cuda?
Why shouldn't I use givens? 
It works with device=gpu and I thought that it is a standard way of processing data in batches.
If it isn't then how do you recommend to do it?

**Comment by ReyhaneAskari** [comment]
Hey @radluki , I double checked it with by using the indexing. The result is still the same thing.  I get the same numbers for CUDA and GPU with the same difference vs CPU in an order of 4e-8:
```python
import numpy as np
import theano
import pickle
import theano.tensor as T
from theano.tensor.nnet import conv2d
import sys
np.random.seed(0)


image_shape = (2, 1, 28, 28)
image = np.asarray(np.random.normal(size=image_shape),
                   dtype=theano.config.floatX)
filter_shape = (100, 1, 5, 5)
filters = np.asarray(np.random.normal(size=filter_shape),
                     dtype=theano.config.floatX)

filters = theano.shared(filters, borrow=True)
image = theano.shared(image, borrow=True)

img = T.tensor4('img')
conv_out = conv2d(
    input=img,
    filters=filters,
    filter_shape=filter_shape,
    input_shape=image_shape)

i = T.lscalar('i')
f = theano.function([i], conv_out, givens={img: image[i:i + 2]})

c_out = np.array(f(0))
print np.sum(np.abs(c_out))
with open(sys.argv[1], 'wb') as f:
    pickle.dump(c_out, f)
```

**Comment by ReyhaneAskari** [comment]
I also re-ran your own code. It had a bug so I fixed it. I know where you had the 0.7 difference. If you don't set the flag to float32 for the CPU, you will get a 0.7 difference between CPU and CUDA. But still the results for CUDA and GPU are the same. So I don't know how you have tested your experiments, you might have made a mistake somewhere when you were defining _floatX_.

```python 
import pickle
import numpy as np
import theano as t
import theano.tensor as T
from theano.tensor.nnet import conv2d
import sys
"""
Script loads data generated by generate_dat.py,
computes convolution and saves result to a file
"""
with open('data.pickle', 'rb') as f:
    d = pickle.load(f)

image = t.shared(d['image'].astype(t.config.floatX), borrow=True)
filters = t.shared(d['filters'].astype(t.config.floatX), borrow=True)
ishape = d['ishape']
fshape = d['fshape']

im1 = T.matrix('im1')
ishape2 = (2,) + ishape[1:]
im2 = im1.reshape(ishape2)
conv_out = conv2d(input=im2,
                  filters=filters,
                  filter_shape=fshape,
                  input_shape=ishape)

i = T.lscalar('i')
eval_conv = t.function([i], [conv_out], givens={im1: image[i:i + 2]})

c_out = np.array(eval_conv(2))
print np.sum(np.abs(c_out))
with open(sys.argv[1], 'wb') as f:
    pickle.dump(c_out, f)
```

**Comment by radluki** [comment]
@ReyhaneAskari , I have checked both files and first one (with seed) gives correct results as you said about 4e-8. However when I run second one I still get 0.7. I have checked also my previous implementation and floatX was set to float32, so that is not the solution to my problem. The value is set in my .theanorc file.

I have noticed that even though your code works for:
```python
image_shape = (2, 1, 28, 28)
c_out = np.array(f(0))
```
when I change those lines to:
```python
image_shape = (20, 1, 28, 28)
c_out = np.array(f(4))
```
I get 0.7 error. I do not want to process whole image at once for specified i. For each i I want to process part of image. I get about 0.7 regardless the seed value. Whole script looks like:
```python
import numpy as np
import theano
import pickle
import theano.tensor as T
from theano.tensor.nnet import conv2d
import sys
np.random.seed(10)


image_shape = (20, 1, 28, 28)
image = np.asarray(np.random.normal(size=image_shape),
                   dtype=theano.config.floatX)
filter_shape = (100, 1, 5, 5)
filters = np.asarray(np.random.normal(size=filter_shape),
                     dtype=theano.config.floatX)

filters = theano.shared(filters, borrow=True)
image = theano.shared(image, borrow=True)

img = T.tensor4('img')
conv_out = conv2d(
    input=img,
    filters=filters,
    filter_shape=filter_shape,
    input_shape=image_shape)

i = T.lscalar('i')
f = theano.function([i], conv_out, givens={img: image[i:i + 2]})

c_out = np.array(f(4))
print(np.sum(np.abs(c_out)) )
with open(sys.argv[1], 'wb') as f:
    pickle.dump(c_out, f)
```
Errors are checked again with:
```python
import pickle
import sys
import numpy as np

with open(sys.argv[1], 'rb') as f:
    d1 = pickle.load(f)

with open(sys.argv[2], 'rb') as f:
    d2 = pickle.load(f)
a1 = np.sum(np.abs(d1))
a2 = np.sum(np.abs(d2))
a3 = a1 + a2
print(np.sum(np.abs(d1 - d2)) / a3)
print(np.allclose(d1, d2,atol=1e-5, rtol=1e-5))
```
Could you check if those scripts give the same results for cuda and cpu? In my case they don't.
The output for gpu/cpu comparison:
```
3.32325e-08
True
```
And cuda/cpu:
```
0.710215
False
```

**Comment by radluki** [comment]
You will probably get correct result. My friend run it today on his computer and the output was similar to my gpu/cpu comparison. Yet, he uses windows operating system and his graphic card supports cuDNN. 
In my case I always get warning:
```
Can not use cuDNN on context None: Device not supported
```
However device=gpu works fine for theano and I can use keras with device=cuda. 
I do not know why though.

**Comment by ReyhaneAskari** [comment]
hey @radluki. Thanks for your follow up responses. I tested the code that you sent and here are my results:

|        | cpu32        | cuda32       | gpu32        |
|--------|--------------|--------------|--------------|
| **cpu64**  | 4.7e-08 True | 4.4e-08 True | 4.4e-08 True |
| **cuda64** | 4.5e-08 True | 4.2e-08 True | 4.2e-08 True |
| **gpu64**  | 4.7e-08 True | 4.4e-08 True | 4.4e-08 True |

So let's do this step by step. I saved this code as test.py : 

```python
import numpy as np
import theano
import pickle
import theano.tensor as T
from theano.tensor.nnet import conv2d
import sys
np.random.seed(10)


image_shape = (20, 1, 28, 28)
image = np.asarray(np.random.normal(size=image_shape),
                   dtype=theano.config.floatX)
filter_shape = (100, 1, 5, 5)
filters = np.asarray(np.random.normal(size=filter_shape),
                     dtype=theano.config.floatX)

filters = theano.shared(filters, borrow=True)
image = theano.shared(image, borrow=True)

img = T.tensor4('img')
conv_out = conv2d(
    input=img,
    filters=filters,
    filter_shape=filter_shape,
    input_shape=image_shape)

i = T.lscalar('i')
f = theano.function([i], conv_out, givens={img: image[i:i + 2]})

c_out = np.array(f(4))
print(np.sum(np.abs(c_out)) )
with open(sys.argv[1], 'wb') as f:
    pickle.dump(c_out, f)
```

and saved this one as compare.py

```python 
import pickle
import sys
import numpy as np

with open(sys.argv[1], 'rb') as f:
    d1 = pickle.load(f)

with open(sys.argv[2], 'rb') as f:
    d2 = pickle.load(f)
a1 = np.sum(np.abs(d1))
a2 = np.sum(np.abs(d2))
a3 = a1 + a2
print(np.sum(np.abs(d1 - d2)) / a3)
print(np.allclose(d1, d2,atol=1e-5, rtol=1e-5))
```

Then I ran the following commands:
``` THEANO_FLAGS='floatX=float32' python test.py cpu_out32```
```THEANO_FLAGS='floatX=float32,device=cuda' python test.py cuda_out32```
```python compare.py cpu_out32 cuda_out32```

Does this give you 0.7 error? Also which version of python are you using?

**Comment by radluki** [comment]
Yes, it gives me 0.710215 and False. I copied all commands and code from your last post. I haven't changed anything. I am using python 3.6.0, but I get the same results when I run it in python 2.7.13.

**Comment by ReyhaneAskari** [comment]
So in python 2.7 you get an error of 5.74159e-08 and in python 3.6 you get an error of 0.7? Do you receive any error or warning when you run it in python 3?  
I tried the same steps in python 3.4.5 and I still get 5.74159e-08, False. How do you switch between python 2 and python 3?

**Comment by radluki** [comment]
No, I always get 0.7 regardless the version of python. The warning that I get is
```
Can not use cuDNN on context None: Device not supported
Mapped name None to device cuda: GeForce GT 820M (0000:01:00.0)
```
I switch simply, by changing commands "... python ..." to "... python2.7...".
When I run device=gpu, I get something like 5e-8 and following warning:
```
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GT 820M (CNMeM is disabled, cuDNN not available)
```
So let's summarise, gpu with old backend works, and new one with libgpuarray does not regardless the version of python. I wouldn't bother, but I get the warning that cuda backend is deprecated and will be removed. And if it will be removed my code eventually will stop working too, as it does not run on libgpuarray. 
Do you understand now? I think I have checked all possibilities, datatypes, conversions to float32 before my first post. Of course you can say, that if I have NVIDIA graphics card and Arch Linux as operating system there may be some problems with gpu controllers, as there are many options to choose from. But all I know is that it all works well with device=gpu.

**Comment by ReyhaneAskari** [comment]
hey @radluki , thanks for your reply. I successfully replicated your results with this command:

```THEANO_FLAGS=device=cuda,floatX=float32,dnn.enabled=False python test.py no_cudnn_cuda32 ```

This gives me 0.7 , false.  So the results are actually different. We will investigate more and let you know.

**Comment by ReyhaneAskari** [comment]
@radluki , so we have found the problem. This is an issue with libgpuarray. It has been fixed now and all you need to do is to upgrade to the latest version of libgpuarray which is  v0.6.5. After updating to the latest version it should no longer give this error.

**Comment by lamblin** [comment]
We believe the issue is solved by using the latest release of libgpuarray, so I'm closing this ticket.

**Comment by schaefer0** [comment]
I'm seeing "Can not use cuDNN on context None: Device not supported"
with 
>>> pygpu.__version__
'0.6.5'
>>> theano.__version__
'0.9.0.dev-1029066eec1c1e37c586eb5f2bf1de212f5b3171'
and 
cuda 8.0

**Comment by lamblin** [comment]
That looks like a totally different problem.
The most likely explanation is that this GPU is too old to support cuDNN. What is your GPU?

**Comment by schaefer0** [comment]
Ok, that makes sense. I only can get the obsolete handoffs from my better funded colleagues : -)

Tesla C2050

On Jun 1, 2017, at 4:37 PM, Pascal Lamblin <notifications@github.com<mailto:notifications@github.com>> wrote:


That looks like a totally different problem.
The most likely explanation is that this GPU is too old to support cuDNN. What is your GPU?

**Comment by lamblin** [comment]
Indeed, Tesla C2050 is of the Fermi generation, with compute capability 2.0, whereas cuDNN requires at least Maxwell (compute capability >= 3.0).
This should not prevent you from using Theano on GPU, though, but some operations may be slower or use more memory.

**Comment by schaefer0** [comment]
Pascal,

I’m doing a proof-of-concept  to find the ion line in ionosphere data (currently plotted by hand), slow should be good enough..

I’ve spent two days trying to install caffe to get to hed (holistically-nested edge detection) and I’m burnt.

At least its Friday.

thanks again,

bob s.

On Jun 2, 2017, at 2:15 PM, Pascal Lamblin <notifications@github.com<mailto:notifications@github.com>> wrote:


Indeed, Tesla C2050 is of the Fermi generation, with compute capability 2.0, whereas cuDNN requires at least Maxwell (compute capability >= 3.0).
This should not prevent you from using Theano on GPU, though, but some operations may be slower or use more memory.

**Comment by ehsanmajidi** [comment]
As I've checked this problem still exists with the the latest release of libgpuarray, or the latest GPUs. 
I'm guessing the problem is with conv2d implementation and its relation to cuDNN. if cuDNN is not available, conv2d result in gpu is like cpu, but when it is enabled the gpu is different from cpu.

**Comment by nouiz** [comment]
Float are not exact number. So changing the back-end can result in small different numerical answer. Just changing the order of addition can cause this. See https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html for more information.

**Comment by ehsanmajidi** [comment]
Yes. However, this error can result in a very large error in a deep network. Is there any solution/feature CPU uses the same floating-point?

**Comment by nouiz** [comment]
You can disable cudnn with this Theano flag:

    dnn.enabled=False

This will force the use of a more similar GPU implementation then what cudnn does. But it isn't a guaranty of having the exact same result. Even on CPU, if you change the BLAS implementation Theano use, you can end up with different result. In fact, with the same CPU BLAS, on comptuters with different CPU, you can get different result.

Otherwise, I think there is some of the cudnn algo that is closer to the CPU convolution we use (it is gemm based). Check the Theano flag: dnn.conv.algo_fwd, dnn.conv.algo_bwd_data, dnn.conv.algo_bwd_filter.

I'm not sure which one is the closest. I guess the default of dnn.conv.algo_fwd is close. For the second one, try the value deterministic, for the last one try small or deterministic.

Using cudnn with different algo should give faster result then not using cudnn on the GPU I think.
