### ISSUE TITLE
RuntimeError: error doing operation: CUDNN_STATUS_INTERNAL_ERROR with new gpuarray backend

### ISSUE THREAD

**Issue by xysszjs** [Theano/Theano#6313]
Hello, I am using theano (0.9.0.dev-RELEASE) with new gpuarray backend (pygpu 0.6.9) and I meet an error during runtime : CUDNN_STATUS_INTERNAL_ERROR (THEANO_FLAGS=device=cuda1,floatX=float32,optimizer_including=cudnn,gpuarray.preallocate=0.9), if I set device=gpu1, there will be no problem.
I have tried rm -rf /home/user/.theano/compiledir_Linux-3.10-e17.x86_64-x86_64-with-centos-7.2.1511-Core-x86_64-2.7.13-64, but it doesn't work. So, how can I deal with it ?
![error](https://user-images.githubusercontent.com/19322065/29352403-274df234-8299-11e7-9723-d851e9af4948.png)

**Comment by nouiz** [comment]
Update to Theano dev version. If that don't fix it, update cudnn to v7. There was fix/workaround for such type of error in both software.

**Comment by xysszjs** [comment]
I tried theano-0.10.0.dev with cudnn-v7, but the error turns into 'pygpu.gpuarray.GpuArrayException'

**Comment by notoraptor** [comment]
@xysszjs Have you purge the cache again (`theano-cache purge`) after you have installed cudnn 7 ?

**Comment by xysszjs** [comment]
Yes, I rm -rf ~/.theano again

**Comment by nouiz** [comment]
We need the full new error to help.

**Comment by nouiz** [comment]
What is the new error?

**Comment by nouiz** [comment]
Now I see the error in your previous comment. The error seem to be due to a shape problem in your graph. Do your graph work on CPU? If not, then you need to fix your computation graph as it does something that don't have a meaning.

**Comment by xysszjs** [comment]
But my graph work successfully without gpuarray backend (device=gpu)，I believe the graph is in good.

**Comment by xysszjs** [comment]
After update theano from 0.10.0dev1.dev-RELEASE to 0.10.0beta1.dev-RELEASE, the error is gone. Thanks
