### ISSUE TITLE
Theano 0.9.0 - Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by Dreyer1416** [Theano/Theano#6417]
Just installed Theano using conda and tried to check if it was using the GPU.

Here is the ouput of the test program in the [tutorial ](http://deeplearning.net/software/theano_versions/dev/tutorial/using_gpu.html):

```
 $ THEANO_FLAGS=device=cuda0 python gpu_tutorial1.py
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/deep/anaconda3/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/home/deep/anaconda3/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/home/deep/anaconda3/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 584, in pygpu.gpuarray.pygpu_init
  File "pygpu/gpuarray.pyx", line 1057, in pygpu.gpuarray.GpuContext.__cinit__
pygpu.gpuarray.GpuArrayException: b'cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory'
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 3.258797 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu

```
Running Ubuntu 16.04/ Cuda 8.0/ python 3.6/ Titan XP

**Comment by nouiz** [comment]
Make sure to use the newest beta release of Theano. With conda:

conda update theano pygpu ligpuarray -c mila-udem

**Comment by Dreyer1416** [comment]
A new error appears after I update to the newest beta release:

```
$ THEANO_FLAGS=device=cuda0 python gpu_tutorial1.py
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.6 or higher required)
NoneType: None
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 3.225526 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu
```

PS: I think there is an typo in the command to install the beta release. shouldn't it be li**b**gpuarray?

**Comment by nouiz** [comment]
Exact about the command line.

What output do you have of

python -c "import pygpu; print pygpu.__version__

**Comment by Dreyer1416** [comment]
0.7.2

Note that I needed to change the command slightly to

python -c "import pygpu; print(pygpu.\_\_version__)"

Since I am using python 3.6

**Comment by Dreyer1416** [comment]
0.9.0.dev-c697eeab84e5b8a74908da654b66ec9eca4f1291

**Comment by notoraptor** [comment]
Ok. So, theano is still not updated to the last version (should be `0.10...`).

Can you retry `conda update theano -c mila-udem` and post the output ?

**Comment by nouiz** [comment]
Before doing the conda update, make sure to uninstall Theano first.

Then conda install theano -c mila-udem

**Comment by Dreyer1416** [comment]
> Can you retry conda update theano -c mila-udem and post the output ?

```
$ conda update theano -c mila-udem
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/deep/anaconda3:
#
theano                    0.9.0                    py36_0  

```

> Before doing the conda update, make sure to uninstall Theano first.

```
$ conda uninstall theano
Fetching package metadata .........
Solving package specifications: .

Package plan for package removal in environment /home/deep/anaconda3:

The following packages will be REMOVED:

    theano: 0.9.0-py36_0

Proceed ([y]/n)? y

```

> Then conda install theano -c mila-udem
```
$ conda install theano -c mila-udem
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/deep/anaconda3:

The following NEW packages will be INSTALLED:

    theano: 0.9.0-py36_0

Proceed ([y]/n)? y
```
Even after uninstalling and reinstalling the version is still 0.9.0

**Comment by nouiz** [comment]
Right, Theano beta isn't installed by default. This should work:

conda update -c mila-udem/label/pre theano

Update the other lib at the same time:


conda update -c mile-udem libgpuarray pygpu

**Comment by Dreyer1416** [comment]
I did  

`conda update -c mila-udem/label/pre theano libgpuarray pygpu`

which updated the packages to the following versions:

```
libgpuarray               0.7.2.dev1           h3972f8e_0    mila-udem/label/pre
pygpu                     0.7.2.dev1       py36he6660cf_0    mila-udem/label/pre
theano                    0.10.0beta2        pyha8067b5_0    mila-udem/label/pre
```
A new error happens now:

```
$ THEANO_FLAGS=device=cuda0 python gpu_tutorial1.py
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/deep/anaconda3/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 204, in <module>
    use(config.device)
  File "/home/deep/anaconda3/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 191, in use
    init_dev(device, preallocate=preallocate)
  File "/home/deep/anaconda3/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 60, in init_dev
    pygpu_version = pygpu_parse_version(pygpu.__version__)
  File "/home/deep/anaconda3/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 51, in pygpu_parse_version
    patch = int(pieces[2].split('+', 1)[0])
ValueError: invalid literal for int() with base 10: '2.dev1'
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 3.038952 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu
```

**Comment by nouiz** [comment]
Thanks for the report. This is now fixed in this PR on Theano:

https://github.com/Theano/Theano/pull/6424

It was our first libgpuarray dev version. So it seam Theano didn't parsed that well!

**Comment by lamblin** [comment]
Closed by #6424.

**Comment by XiaoqiaoChen** [comment]
@nouiz Why do I still have the totally same problems?

**Comment by nouiz** [comment]
Which error? There was a few in this issue. Can you give your full error? small detail could give different reason. Do you use the github version of Theano? When did you update it? If not, which version of Theano do you use?

**Comment by msiraj83** [comment]
@nouiz ...thanks .... it work for me and the remove the error....

`conda update theano pygpu libgpuarray -c mila-udem`

**Comment by bricksdont** [comment]
@nouiz I'm also getting

    ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

Does the newest release candidate require a specific version of cuDNN?

**Comment by nouiz** [comment]
This error isn't related to cudnn. try just "import pygpu" it could give you a better error. Theano 1.0rc1 need pygpu version 0.7*

**Comment by bricksdont** [comment]
```python
$ python -c "import pygpu"
```

does not give me an error at all, but:

```python
$ python -c "import theano"
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/mnt/storage/clfiles/projects/clresources/resources/applications/toolkit/anaconda/v2curr/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 220, in <module>
    use(config.device)
  File "/mnt/storage/clfiles/projects/clresources/resources/applications/toolkit/anaconda/v2curr/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 207, in use
    init_dev(device, preallocate=preallocate)
  File "/mnt/storage/clfiles/projects/clresources/resources/applications/toolkit/anaconda/v2curr/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 110, in init_dev
    context.cudnn_handle = dnn._make_handle(context)
  File "/mnt/storage/clfiles/projects/clresources/resources/applications/toolkit/anaconda/v2curr/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 118, in _make_handle
    cudnn = _dnn_lib()
  File "/mnt/storage/clfiles/projects/clresources/resources/applications/toolkit/anaconda/v2curr/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 105, in _dnn_lib
    raise RuntimeError('Could not load cudnn library')
RuntimeError: Could not load cudnn library
```

**Comment by nouiz** [comment]
where is the libcudnn.so file? What is the output of:

python -c "import theano; print(theano.config.dnn.bin_path"

Fred

**Comment by bricksdont** [comment]
Yes, that's the culprit. See my update above - thanks for your help!
