### ISSUE TITLE
Import theano : CUDA_ERROR_UNKNOWN 

### ISSUE THREAD

**Issue by massimilianocomin** [Theano/Theano#6531]
Hello,

I just upgraded to Theano 1.0.0 on a GPU cluster (CentOS 6.9) using the command 
`conda uninstall theano pygpu libgpuarray`
`conda install -c mila-udem theano pygpu`

When I try to import theano I get the following :

`WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.`
`ERROR (theano.gpuarray): Could not initialize pygpu, support disabled`
`Traceback (most recent call last):`
`File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 220, in <module>`
    `use(config.device)`
  `File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 207, in use`
   ` init_dev(device, preallocate=preallocate)`
  `File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 94, in init_dev
    **args)`
  `File "pygpu/gpuarray.pyx", line 651, in pygpu.gpuarray.init`
 ` File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init`
`pygpu.gpuarray.GpuArrayException: b'cuInit: CUDA_ERROR_UNKNOWN: unknown error'`

On the other hand, importing pygpu gives no trouble. I have Theano 1.0.0, pygpu and libgpuarray 0.7.5.

Thank you for helping !

**Comment by notoraptor** [comment]
Hi, it's quite strange.

Could you clear theano cache (`theano-cache purge`) and then retry to import theano ?

Also, could you retry to import pygpu with the following code ?
```python
import pygpu
ctx = pygpu.init('cuda')
print(ctx.devname)
```

**Comment by massimilianocomin** [comment]
Sorry I forgot to mention I cleared theano cache. It printed a lot of similar errors and the problem remained.

When running `ctx = pygpu.init('cuda')` I get :
`  File "<stdin>", line 1, in <module>`
`  File "pygpu/gpuarray.pyx", line 651, in pygpu.gpuarray.init`
`  File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init`
`pygpu.gpuarray.GpuArrayException: b'cuInit: CUDA_ERROR_UNKNOWN: unknown error'`

**Comment by notoraptor** [comment]
Which version of CUDA do you use ? What is your GPU (what is the output of `nvidia-smi`) ?

**Comment by massimilianocomin** [comment]
Hi,

It turns out that I had two theano installed, after deleting everything and reinstalling and clearing cache it works fine. 

Sorry for the useless issue !

**Comment by chcgnzls** [comment]
I am getting the same error but I not due to the same issue. I am using CUDA 8.0

`ctx = pygpu.init('cuda')` gives: `Tesla K20Xm`

`nvidia-smi`:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.26                 Driver Version: 387.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K20Xm         Off  | 00000000:84:00.0 Off |                    0 |
| N/A   20C    P0    60W / 235W |      0MiB /  5699MiB |     98%   E. Process |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
